/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_ai_model_insights_summary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAiModelInsightsSummaryError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_ai_model_position_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAiModelPositionDistributionError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_ai_overview_results`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAiOverviewResultsError {
    UnknownValue(serde_json::Value),
}


/// Per-model mentions, citations, brand net sentiment with raw counts, weighted visibility totals/shares, plus actor matrices. All actor entries use the standard shape `{ type, id, competitor_id, name, domain }` with bare (scheme-less) domains.
pub async fn get_ai_model_insights_summary(configuration: &configuration::Configuration, project_id: i32, range: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, granularity: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt_type: Option<&str>, brand_kind: Option<&str>, competitors: Option<&str>) -> Result<(), Error<GetAiModelInsightsSummaryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_range = range;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_granularity = granularity;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt_type = prompt_type;
    let p_query_brand_kind = brand_kind;
    let p_query_competitors = competitors;

    let uri_str = format!("{}/reports/ai_model_insights/summary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_range {
        req_builder = req_builder.query(&[("range", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_granularity {
        req_builder = req_builder.query(&[("granularity", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt_type {
        req_builder = req_builder.query(&[("prompt_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAiModelInsightsSummaryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_ai_model_position_distribution(configuration: &configuration::Configuration, project_id: i32, range: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, granularity: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt_type: Option<&str>, brand_kind: Option<&str>, model: Option<&str>, brand1: Option<i32>, brand2: Option<i32>) -> Result<(), Error<GetAiModelPositionDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_range = range;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_granularity = granularity;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt_type = prompt_type;
    let p_query_brand_kind = brand_kind;
    let p_query_model = model;
    let p_query_brand1 = brand1;
    let p_query_brand2 = brand2;

    let uri_str = format!("{}/reports/ai_model_insights/position_distribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_range {
        req_builder = req_builder.query(&[("range", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_granularity {
        req_builder = req_builder.query(&[("granularity", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt_type {
        req_builder = req_builder.query(&[("prompt_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand1 {
        req_builder = req_builder.query(&[("brand1", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand2 {
        req_builder = req_builder.query(&[("brand2", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAiModelPositionDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_ai_overview_results(configuration: &configuration::Configuration, project_id: i32, range: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, granularity: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt_type: Option<&str>, brand_kind: Option<&str>, page: Option<u32>, per_page: Option<u32>) -> Result<(), Error<GetAiOverviewResultsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_range = range;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_granularity = granularity;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt_type = prompt_type;
    let p_query_brand_kind = brand_kind;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/reports/ai_model_insights/ai_overview_results", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_range {
        req_builder = req_builder.query(&[("range", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_granularity {
        req_builder = req_builder.query(&[("granularity", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt_type {
        req_builder = req_builder.query(&[("prompt_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAiOverviewResultsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

