/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`list_all_citations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAllCitationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_all_mentions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListAllMentionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_citations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCitationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_competitor_citations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCompetitorCitationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_competitor_mentions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCompetitorMentionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_mentions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMentionsError {
    UnknownValue(serde_json::Value),
}


/// Unified citations stream with an `actor_type` field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
pub async fn list_all_citations(configuration: &configuration::Configuration, project_id: i32, competitors: Option<&str>, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListAllCitationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_competitors = competitors;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/all_citations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListAllCitationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Unified mentions stream. Each record has an `actor_type` field (`project` or `competitor`) so the same payload covers both.
pub async fn list_all_mentions(configuration: &configuration::Configuration, project_id: i32, competitors: Option<&str>, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListAllMentionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_competitors = competitors;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/all_mentions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListAllMentionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
pub async fn list_citations(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListCitationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/citations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCitationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
pub async fn list_competitor_citations(configuration: &configuration::Configuration, project_id: i32, competitors: Option<&str>, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListCompetitorCitationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_competitors = competitors;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/competitor_citations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCompetitorCitationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_competitor_mentions(configuration: &configuration::Configuration, project_id: i32, competitors: Option<&str>, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListCompetitorMentionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_competitors = competitors;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/competitor_mentions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCompetitorMentionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_mentions(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListMentionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/mentions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMentionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

