/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_prompts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePromptsError {
    Status403(models::ApiError),
    Status422(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_prompt`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePromptError {
    Status403(models::ApiError),
    Status404(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_prompt_executions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListPromptExecutionsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_prompts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListPromptsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_query_fan_outs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListQueryFanOutsError {
    Status422(models::ApiError),
    UnknownValue(serde_json::Value),
}


/// Add prompts to a project in bulk (up to 100 per request). Validates the account prompt quota and skips duplicates. Requires a `read_write` scope API key.
pub async fn create_prompts(configuration: &configuration::Configuration, prompts_create_request: models::PromptsCreateRequest) -> Result<models::PromptsCreateResponse, Error<CreatePromptsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_prompts_create_request = prompts_create_request;

    let uri_str = format!("{}/prompts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_prompts_create_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PromptsCreateResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PromptsCreateResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePromptsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes a prompt (irreversible). The prompt disappears immediately and frees a prompt slot; its historical data (executions, mentions, citations, sentiment) is purged by a background job. Requires a `read_write` scope API key.
pub async fn delete_prompt(configuration: &configuration::Configuration, project_id: i32, id: i32) -> Result<(), Error<DeletePromptError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_path_id = id;

    let uri_str = format!("{}/prompts/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeletePromptError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_prompt_executions(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<&str>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, mention_filter: Option<&str>, citation_filter: Option<&str>, competitors: Option<&str>, output: Option<&str>) -> Result<(), Error<ListPromptExecutionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_mention_filter = mention_filter;
    let p_query_citation_filter = citation_filter;
    let p_query_competitors = competitors;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/prompt_executions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_mention_filter {
        req_builder = req_builder.query(&[("mention_filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_citation_filter {
        req_builder = req_builder.query(&[("citation_filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListPromptExecutionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_prompts(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<&str>, country_code: Option<&str>, language_code: Option<&str>, prompt_type: Option<&str>, brand_kind: Option<&str>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListPromptsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt_type = prompt_type;
    let p_query_brand_kind = brand_kind;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/prompts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt_type {
        req_builder = req_builder.query(&[("prompt_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListPromptsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The sub-queries a model actually issued when answering your tracked prompts. view=query (default) returns one row per distinct sub-query with count and share of all occurrences; view=prompt returns one row per prompt with how many distinct sub-queries it produced. Fan-out is reported mainly by ChatGPT, so an empty result usually means the models in scope do not expose it. The API returns the aggregation only: for a period-over-period delta, call it twice with explicit from/to.
pub async fn list_query_fan_outs(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, view: Option<&str>, order: Option<&str>, direction: Option<&str>, query: Option<&str>, model: Option<&str>, collection_id: Option<&str>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, prompt_type: Option<&str>, brand_kind: Option<&str>, range: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, output: Option<&str>) -> Result<(), Error<ListQueryFanOutsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_view = view;
    let p_query_order = order;
    let p_query_direction = direction;
    let p_query_query = query;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_prompt_type = prompt_type;
    let p_query_brand_kind = brand_kind;
    let p_query_range = range;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/query_fan_outs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_view {
        req_builder = req_builder.query(&[("view", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_direction {
        req_builder = req_builder.query(&[("direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt_type {
        req_builder = req_builder.query(&[("prompt_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_range {
        req_builder = req_builder.query(&[("range", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListQueryFanOutsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

