/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_cited_url_content`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCitedUrlContentError {
    Status404(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_cited_url_detail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCitedUrlDetailError {
    Status404(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_mentions_by_citing_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetMentionsByCitingDomainError {
    Status422(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_citation_groups`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCitationGroupsError {
    Status422(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_cited_url_occurrences`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCitedUrlOccurrencesError {
    Status404(models::ApiError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sources`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSourcesError {
    UnknownValue(serde_json::Value),
}


/// Unavailable page content keeps the cited URL and citation metrics. Page metadata/content and unknown brand_mentioned/competitor_mentioned return null; content_gap_status is content_unavailable (or missing_page_cache). Mention arrays stay empty until usable content has completed analysis. status_code shows a saved successful response or observed 404/410; other crawl failures and error_message are hidden. last_crawled_at dates the saved copy. Domain/host crawled_urls_count counts usable copies; mention counts are null when no URL has completed analysis.
pub async fn get_cited_url_content(configuration: &configuration::Configuration, project_id: i32, url_sha256: &str) -> Result<(), Error<GetCitedUrlContentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_path_url_sha256 = url_sha256;

    let uri_str = format!("{}/citation_intelligence/urls/{url_sha256}/content", configuration.base_path, url_sha256=crate::apis::urlencode(p_path_url_sha256));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCitedUrlContentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Unavailable page content keeps the cited URL and citation metrics. Page metadata/content and unknown brand_mentioned/competitor_mentioned return null; content_gap_status is content_unavailable (or missing_page_cache). Mention arrays stay empty until usable content has completed analysis. status_code shows a saved successful response or observed 404/410; other crawl failures and error_message are hidden. last_crawled_at dates the saved copy. Domain/host crawled_urls_count counts usable copies; mention counts are null when no URL has completed analysis.
pub async fn get_cited_url_detail(configuration: &configuration::Configuration, project_id: i32, url_sha256: &str) -> Result<(), Error<GetCitedUrlDetailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_path_url_sha256 = url_sha256;

    let uri_str = format!("{}/citation_intelligence/urls/{url_sha256}", configuration.base_path, url_sha256=crate::apis::urlencode(p_path_url_sha256));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCitedUrlDetailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// For the responses where each given source domain is cited, returns the share of those responses that mention the brand vs each competitor (brand + competitors sum to 100% per domain). Pass multiple domains to get the whole matrix in one call.
pub async fn get_mentions_by_citing_domain(configuration: &configuration::Configuration, project_id: i32, domains: Vec<String>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, brand_kind: Option<&str>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>) -> Result<(), Error<GetMentionsByCitingDomainError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_domains = domains;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_brand_kind = brand_kind;
    let p_query_from = from;
    let p_query_to = to;

    let uri_str = format!("{}/citation_intelligence/mentions_by_domain", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    req_builder = match "multi" {
        "multi" => req_builder.query(&p_query_domains.into_iter().map(|p| ("domains".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
        _ => req_builder.query(&[("domains", &p_query_domains.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
    };
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_brand_kind {
        req_builder = req_builder.query(&[("brand_kind", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetMentionsByCitingDomainError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Grouped citation intelligence by url / domain / host with per-model breakdown, citation rate, and avg citation position. Counts and citation rate include visible citations and background source references. Average position ignores rows with position=0. Owned and competitor source matching honor the project's exact-subdomain setting. Filter vocabulary aligns with `source_type` returned by the API. Unavailable page content keeps the cited URL and citation metrics. Page metadata/content and unknown brand_mentioned/competitor_mentioned return null; content_gap_status is content_unavailable (or missing_page_cache). Mention arrays stay empty until usable content has completed analysis. status_code shows a saved successful response or observed 404/410; other crawl failures and error_message are hidden. last_crawled_at dates the saved copy. Domain/host crawled_urls_count counts usable copies; mention counts are null when no URL has completed analysis.
pub async fn list_citation_groups(configuration: &configuration::Configuration, project_id: i32, view: Option<&str>, page: Option<u32>, per_page: Option<u32>, order: Option<&str>, direction: Option<&str>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, query: Option<&str>, source_type: Option<&str>, sentiment: Option<&str>, content_gap: Option<&str>) -> Result<(), Error<ListCitationGroupsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_view = view;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_order = order;
    let p_query_direction = direction;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_query = query;
    let p_query_source_type = source_type;
    let p_query_sentiment = sentiment;
    let p_query_content_gap = content_gap;

    let uri_str = format!("{}/citation_intelligence/groups", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_view {
        req_builder = req_builder.query(&[("view", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_direction {
        req_builder = req_builder.query(&[("direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_source_type {
        req_builder = req_builder.query(&[("source_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sentiment {
        req_builder = req_builder.query(&[("sentiment", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_content_gap {
        req_builder = req_builder.query(&[("content_gap", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCitationGroupsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_cited_url_occurrences(configuration: &configuration::Configuration, project_id: i32, url_sha256: &str, page: Option<u32>, per_page: Option<u32>) -> Result<(), Error<ListCitedUrlOccurrencesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_path_url_sha256 = url_sha256;
    let p_query_page = page;
    let p_query_per_page = per_page;

    let uri_str = format!("{}/citation_intelligence/urls/{url_sha256}/occurrences", configuration.base_path, url_sha256=crate::apis::urlencode(p_path_url_sha256));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCitedUrlOccurrencesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_sources(configuration: &configuration::Configuration, project_id: i32, page: Option<u32>, per_page: Option<u32>, model: Option<&str>, collection_id: Option<models::GetTimeseriesCollectionIdParameter>, country_code: Option<&str>, language_code: Option<&str>, prompt: Option<i32>, from: Option<chrono::DateTime<chrono::FixedOffset>>, to: Option<chrono::DateTime<chrono::FixedOffset>>, source_type: Option<&str>, mention_filter: Option<&str>, competitors: Option<&str>, output: Option<&str>) -> Result<(), Error<ListSourcesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project_id = project_id;
    let p_query_page = page;
    let p_query_per_page = per_page;
    let p_query_model = model;
    let p_query_collection_id = collection_id;
    let p_query_country_code = country_code;
    let p_query_language_code = language_code;
    let p_query_prompt = prompt;
    let p_query_from = from;
    let p_query_to = to;
    let p_query_source_type = source_type;
    let p_query_mention_filter = mention_filter;
    let p_query_competitors = competitors;
    let p_query_output = output;

    let uri_str = format!("{}/dimensions/sources", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("project_id", &p_query_project_id.to_string())]);
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_model {
        req_builder = req_builder.query(&[("model", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_collection_id {
        req_builder = req_builder.query(&[("collection_id", &serde_json::to_string(param_value)?)]);
    }
    if let Some(ref param_value) = p_query_country_code {
        req_builder = req_builder.query(&[("country_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language_code {
        req_builder = req_builder.query(&[("language_code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_prompt {
        req_builder = req_builder.query(&[("prompt", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_source_type {
        req_builder = req_builder.query(&[("source_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_mention_filter {
        req_builder = req_builder.query(&[("mention_filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_competitors {
        req_builder = req_builder.query(&[("competitors", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_output {
        req_builder = req_builder.query(&[("output", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSourcesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

