/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountQuota : A consumable quota. limit and remaining are null when unlimited is true. For a key limited to some projects, prompts and intelligence_tasks carry no limit (and intelligence_tasks no used): only the capacity left.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountQuota {
    #[serde(rename = "limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub limit: Option<Option<i32>>,
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i32>,
    #[serde(rename = "remaining", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remaining: Option<Option<i32>>,
    #[serde(rename = "unlimited", skip_serializing_if = "Option::is_none")]
    pub unlimited: Option<bool>,
    /// Reset window for quotas that reset (e.g. month)
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
}

impl AccountQuota {
    /// A consumable quota. limit and remaining are null when unlimited is true. For a key limited to some projects, prompts and intelligence_tasks carry no limit (and intelligence_tasks no used): only the capacity left.
    pub fn new() -> AccountQuota {
        AccountQuota {
            limit: None,
            used: None,
            remaining: None,
            unlimited: None,
            period: None,
        }
    }
}

