/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentTrafficResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::NaiveDate>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<chrono::NaiveDate>,
    #[serde(rename = "group_by", skip_serializing_if = "Option::is_none")]
    pub group_by: Option<GroupBy>,
    #[serde(rename = "granularity", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<Granularity>,
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "timeseries", skip_serializing_if = "Option::is_none")]
    pub timeseries: Option<std::collections::HashMap<String, std::collections::HashMap<String, i32>>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl AgentTrafficResponse {
    pub fn new() -> AgentTrafficResponse {
        AgentTrafficResponse {
            project_id: None,
            from: None,
            to: None,
            group_by: None,
            granularity: None,
            totals: None,
            timeseries: None,
            request_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupBy {
    #[serde(rename = "bot")]
    Bot,
    #[serde(rename = "company")]
    Company,
}

impl Default for GroupBy {
    fn default() -> GroupBy {
        Self::Bot
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Granularity {
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,
}

impl Default for Granularity {
    fn default() -> Granularity {
        Self::Day
    }
}

