/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersResponseTotals {
    #[serde(rename = "orders")]
    pub orders: i32,
    /// Decimal amount with two decimals, e.g. 1834.20
    #[serde(rename = "revenue")]
    pub revenue: String,
}

impl AiOrdersResponseTotals {
    pub fn new(orders: i32, revenue: String) -> AiOrdersResponseTotals {
        AiOrdersResponseTotals {
            orders,
            revenue,
        }
    }
}

