/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersResponseSeriesInner {
    #[serde(rename = "day")]
    pub day: chrono::NaiveDate,
    #[serde(rename = "orders")]
    pub orders: i32,
    #[serde(rename = "revenue")]
    pub revenue: String,
}

impl AiOrdersResponseSeriesInner {
    pub fn new(day: chrono::NaiveDate, orders: i32, revenue: String) -> AiOrdersResponseSeriesInner {
        AiOrdersResponseSeriesInner {
            day,
            orders,
            revenue,
        }
    }
}

