/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersResponseBySourceInner {
    /// AI assistant slug, e.g. chatgpt or perplexity
    #[serde(rename = "source")]
    pub source: String,
    /// Display name, e.g. ChatGPT
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "orders")]
    pub orders: i32,
    #[serde(rename = "revenue")]
    pub revenue: String,
}

impl AiOrdersResponseBySourceInner {
    pub fn new(source: String, name: String, orders: i32, revenue: String) -> AiOrdersResponseBySourceInner {
        AiOrdersResponseBySourceInner {
            source,
            name,
            orders,
            revenue,
        }
    }
}

