/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersUpdateRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "platform")]
    pub platform: Platform,
    /// ISO 4217 code, e.g. EUR
    #[serde(rename = "currency")]
    pub currency: String,
    /// First day of the window this push replaces
    #[serde(rename = "from")]
    pub from: chrono::NaiveDate,
    /// Last day of the window; at most 400 days after from
    #[serde(rename = "to")]
    pub to: chrono::NaiveDate,
    #[serde(rename = "days")]
    pub days: Vec<models::AiOrdersUpdateRequestDaysInner>,
}

impl AiOrdersUpdateRequest {
    pub fn new(project_id: i32, platform: Platform, currency: String, from: chrono::NaiveDate, to: chrono::NaiveDate, days: Vec<models::AiOrdersUpdateRequestDaysInner>) -> AiOrdersUpdateRequest {
        AiOrdersUpdateRequest {
            project_id,
            platform,
            currency,
            from,
            to,
            days,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platform {
    #[serde(rename = "shopify")]
    Shopify,
}

impl Default for Platform {
    fn default() -> Platform {
        Self::Shopify
    }
}

