/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersUpdateResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "platform")]
    pub platform: String,
    /// Rows stored, one per day and AI assistant
    #[serde(rename = "stored")]
    pub stored: i32,
    /// Entries whose referrer is not an AI assistant
    #[serde(rename = "ignored")]
    pub ignored: i32,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AiOrdersUpdateResponse {
    pub fn new(project_id: i32, platform: String, stored: i32, ignored: i32, request_id: String) -> AiOrdersUpdateResponse {
        AiOrdersUpdateResponse {
            project_id,
            platform,
            stored,
            ignored,
            request_id,
        }
    }
}

