/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "platform")]
    pub platform: String,
    /// ISO 4217 code of the most recent stored day; null when the window holds no stored order
    #[serde(rename = "currency", deserialize_with = "Option::deserialize")]
    pub currency: Option<String>,
    #[serde(rename = "from")]
    pub from: chrono::NaiveDate,
    #[serde(rename = "to")]
    pub to: chrono::NaiveDate,
    #[serde(rename = "totals")]
    pub totals: Box<models::AiOrdersResponseTotals>,
    /// One row per AI assistant, highest revenue first
    #[serde(rename = "by_source")]
    pub by_source: Vec<models::AiOrdersResponseBySourceInner>,
    /// Days that have stored orders, oldest first
    #[serde(rename = "series")]
    pub series: Vec<models::AiOrdersResponseSeriesInner>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AiOrdersResponse {
    pub fn new(project_id: i32, platform: String, currency: Option<String>, from: chrono::NaiveDate, to: chrono::NaiveDate, totals: models::AiOrdersResponseTotals, by_source: Vec<models::AiOrdersResponseBySourceInner>, series: Vec<models::AiOrdersResponseSeriesInner>, request_id: String) -> AiOrdersResponse {
        AiOrdersResponse {
            project_id,
            platform,
            currency,
            from,
            to,
            totals: Box::new(totals),
            by_source,
            series,
            request_id,
        }
    }
}

