/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiOrdersUpdateRequestDaysInner {
    /// Must fall inside from..to
    #[serde(rename = "day")]
    pub day: chrono::NaiveDate,
    /// Raw referring host or utm_source of the order's first visit, e.g. chatgpt.com. Entries that are not an AI assistant are ignored
    #[serde(rename = "referrer")]
    pub referrer: String,
    #[serde(rename = "orders")]
    pub orders: u32,
    /// Non-negative decimal amount in currency, e.g. 120.50. A JSON number is accepted too
    #[serde(rename = "revenue")]
    pub revenue: String,
}

impl AiOrdersUpdateRequestDaysInner {
    pub fn new(day: chrono::NaiveDate, referrer: String, orders: u32, revenue: String) -> AiOrdersUpdateRequestDaysInner {
        AiOrdersUpdateRequestDaysInner {
            day,
            referrer,
            orders,
            revenue,
        }
    }
}

