/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotationCreateResponseAnnotation {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "annotation_date")]
    pub annotation_date: chrono::NaiveDate,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    /// Hex color such as '#4F46E5'
    #[serde(rename = "color", deserialize_with = "Option::deserialize")]
    pub color: Option<String>,
    #[serde(rename = "annotation_category_id", deserialize_with = "Option::deserialize")]
    pub annotation_category_id: Option<i32>,
}

impl AnnotationCreateResponseAnnotation {
    pub fn new(id: i32, title: String, annotation_date: chrono::NaiveDate, description: Option<String>, color: Option<String>, annotation_category_id: Option<i32>) -> AnnotationCreateResponseAnnotation {
        AnnotationCreateResponseAnnotation {
            id,
            title,
            annotation_date,
            description,
            color,
            annotation_category_id,
        }
    }
}

