/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotationCreateResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "annotation")]
    pub annotation: Box<models::AnnotationCreateResponseAnnotation>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AnnotationCreateResponse {
    pub fn new(project_id: i32, annotation: models::AnnotationCreateResponseAnnotation, request_id: String) -> AnnotationCreateResponse {
        AnnotationCreateResponse {
            project_id,
            annotation: Box::new(annotation),
            request_id,
        }
    }
}

