/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorError {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<Code>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
}

impl ApiErrorError {
    pub fn new() -> ApiErrorError {
        ApiErrorError {
            code: None,
            message: None,
            meta: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "ERR_MISSING_AUTH")]
    ErrMissingAuth,
    #[serde(rename = "ERR_INVALID_API_KEY")]
    ErrInvalidApiKey,
    #[serde(rename = "ERR_REVOKED_API_KEY")]
    ErrRevokedApiKey,
    #[serde(rename = "ERR_INSUFFICIENT_SCOPE")]
    ErrInsufficientScope,
    #[serde(rename = "ERR_INSUFFICIENT_PERMISSION")]
    ErrInsufficientPermission,
    #[serde(rename = "ERR_PLAN_REQUIRED")]
    ErrPlanRequired,
    #[serde(rename = "ERR_ACCOUNT_INACTIVE")]
    ErrAccountInactive,
    #[serde(rename = "ERR_DRAFT_NOT_FOUND")]
    ErrDraftNotFound,
    #[serde(rename = "ERR_DRAFT_STATE")]
    ErrDraftState,
    #[serde(rename = "ERR_PROJECT_NOT_FOUND")]
    ErrProjectNotFound,
    #[serde(rename = "ERR_NOT_FOUND")]
    ErrNotFound,
    #[serde(rename = "ERR_SEARCH_CONSOLE_NOT_CONNECTED")]
    ErrSearchConsoleNotConnected,
    #[serde(rename = "ERR_SEARCH_CONSOLE_ACCESS_REVOKED")]
    ErrSearchConsoleAccessRevoked,
    #[serde(rename = "ERR_SEARCH_CONSOLE_UPSTREAM")]
    ErrSearchConsoleUpstream,
    #[serde(rename = "ERR_AI_TRAFFIC_NOT_CONNECTED")]
    ErrAiTrafficNotConnected,
    #[serde(rename = "ERR_AGENT_TRAFFIC_NOT_CONNECTED")]
    ErrAgentTrafficNotConnected,
    #[serde(rename = "ERR_INVALID_PARAM")]
    ErrInvalidParam,
    #[serde(rename = "ERR_INVALID_RANGE")]
    ErrInvalidRange,
    #[serde(rename = "ERR_LIMIT_REACHED")]
    ErrLimitReached,
    #[serde(rename = "ERR_QUOTA_EXCEEDED")]
    ErrQuotaExceeded,
    #[serde(rename = "ERR_RATE_LIMITED")]
    ErrRateLimited,
}

impl Default for Code {
    fn default() -> Code {
        Self::ErrMissingAuth
    }
}

