/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPromptSuggestionsAcceptResponseSkippedInner {
    #[serde(rename = "suggestion_id")]
    pub suggestion_id: i32,
    /// accepted or rejected (the suggestion was no longer pending), or pending_deletion
    #[serde(rename = "reason")]
    pub reason: String,
}

impl CatalogPromptSuggestionsAcceptResponseSkippedInner {
    pub fn new(suggestion_id: i32, reason: String) -> CatalogPromptSuggestionsAcceptResponseSkippedInner {
        CatalogPromptSuggestionsAcceptResponseSkippedInner {
            suggestion_id,
            reason,
        }
    }
}

