/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPromptSuggestionsAcceptResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "accepted")]
    pub accepted: Vec<models::CatalogPromptSuggestionsAcceptResponseAcceptedInner>,
    #[serde(rename = "skipped")]
    pub skipped: Vec<models::CatalogPromptSuggestionsAcceptResponseSkippedInner>,
    /// Prompt slots left on the plan; null when unlimited
    #[serde(rename = "prompts_available", deserialize_with = "Option::deserialize")]
    pub prompts_available: Option<i32>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CatalogPromptSuggestionsAcceptResponse {
    pub fn new(project_id: i32, accepted: Vec<models::CatalogPromptSuggestionsAcceptResponseAcceptedInner>, skipped: Vec<models::CatalogPromptSuggestionsAcceptResponseSkippedInner>, prompts_available: Option<i32>, request_id: String) -> CatalogPromptSuggestionsAcceptResponse {
        CatalogPromptSuggestionsAcceptResponse {
            project_id,
            accepted,
            skipped,
            prompts_available,
            request_id,
        }
    }
}

