/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPromptSuggestionsRejectResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "rejected")]
    pub rejected: i32,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CatalogPromptSuggestionsRejectResponse {
    pub fn new(project_id: i32, rejected: i32, request_id: String) -> CatalogPromptSuggestionsRejectResponse {
        CatalogPromptSuggestionsRejectResponse {
            project_id,
            rejected,
            request_id,
        }
    }
}

