/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPromptSuggestionsResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "data")]
    pub data: Vec<models::CatalogPromptSuggestion>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CatalogPromptSuggestionsResponse {
    pub fn new(project_id: i32, page: i32, per_page: i32, total: i32, data: Vec<models::CatalogPromptSuggestion>, request_id: String) -> CatalogPromptSuggestionsResponse {
        CatalogPromptSuggestionsResponse {
            project_id,
            page,
            per_page,
            total,
            data,
            request_id,
        }
    }
}

