/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogPromptSuggestionProduct : The catalog product the suggestion was written for
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPromptSuggestionProduct {
    /// The store's product id, e.g. gid://shopify/Product/1
    #[serde(rename = "external_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<Option<String>>,
    #[serde(rename = "handle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub handle: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
}

impl CatalogPromptSuggestionProduct {
    /// The catalog product the suggestion was written for
    pub fn new() -> CatalogPromptSuggestionProduct {
        CatalogPromptSuggestionProduct {
            external_id: None,
            handle: None,
            title: None,
        }
    }
}

