/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CitationMatchMode : How citations are attributed: domain (the domain and its subdomains), host (that exact host) or path_prefix (URLs under citation_match_path)
/// How citations are attributed: domain (the domain and its subdomains), host (that exact host) or path_prefix (URLs under citation_match_path)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CitationMatchMode {
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "host")]
    Host,
    #[serde(rename = "path_prefix")]
    PathPrefix,

}

impl std::fmt::Display for CitationMatchMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Domain => write!(f, "domain"),
            Self::Host => write!(f, "host"),
            Self::PathPrefix => write!(f, "path_prefix"),
        }
    }
}

impl Default for CitationMatchMode {
    fn default() -> CitationMatchMode {
        Self::Domain
    }
}

