/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CitationRecord {
    #[serde(rename = "id")]
    pub id: i32,
    /// The project's brand name (its name when no brand name is set)
    #[serde(rename = "name")]
    pub name: String,
    /// Host of the cited URL without www.; null when the URL has no parsable host
    #[serde(rename = "domain", deserialize_with = "Option::deserialize")]
    pub domain: Option<String>,
    #[serde(rename = "prompt_id")]
    pub prompt_id: i32,
    #[serde(rename = "prompt_execution_id")]
    pub prompt_execution_id: i32,
    /// Normalized cited URL (tracking parameters and fragment removed)
    #[serde(rename = "url")]
    pub url: String,
    /// Rank of the citation in the answer; 0 for a background source reference with no visible rank
    #[serde(rename = "position", deserialize_with = "Option::deserialize")]
    pub position: Option<i32>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CitationRecord {
    pub fn new(id: i32, name: String, domain: Option<String>, prompt_id: i32, prompt_execution_id: i32, url: String, position: Option<i32>, created_at: chrono::DateTime<chrono::FixedOffset>) -> CitationRecord {
        CitationRecord {
            id,
            name,
            domain,
            prompt_id,
            prompt_execution_id,
            url,
            position,
            created_at,
        }
    }
}

