/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionsResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "collections")]
    pub collections: Vec<models::TagRef>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl CollectionsResponse {
    pub fn new(project_id: i32, collections: Vec<models::TagRef>, request_id: String) -> CollectionsResponse {
        CollectionsResponse {
            project_id,
            collections,
            request_id,
        }
    }
}

