/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Competitor {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    /// Only present when include_project_brand=true
    #[serde(rename = "actor_type", skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<ActorType>,
    /// Only present when include_project_brand=true
    #[serde(rename = "is_own", skip_serializing_if = "Option::is_none")]
    pub is_own: Option<bool>,
}

impl Competitor {
    pub fn new() -> Competitor {
        Competitor {
            id: None,
            name: None,
            domain: None,
            actor_type: None,
            is_own: None,
        }
    }
}
/// Only present when include_project_brand=true
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActorType {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "competitor")]
    Competitor,
}

impl Default for ActorType {
    fn default() -> ActorType {
        Self::Project
    }
}

