/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitorDetails {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "matching_names", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Option<Vec<String>>>,
    #[serde(rename = "google_play_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub google_play_id: Option<Option<String>>,
    #[serde(rename = "app_store_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub app_store_id: Option<Option<String>>,
    #[serde(rename = "citation_match_mode", skip_serializing_if = "Option::is_none")]
    pub citation_match_mode: Option<models::CitationMatchMode>,
    /// Set only when citation_match_mode is path_prefix
    #[serde(rename = "citation_match_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub citation_match_path: Option<Option<String>>,
    /// English app name on Google Play, when the competitor has an Android app
    #[serde(rename = "google_play_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub google_play_name: Option<Option<String>>,
    /// English app name on the App Store, when the competitor has an iOS app
    #[serde(rename = "app_store_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub app_store_name: Option<Option<String>>,
    #[serde(rename = "google_play_icon_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub google_play_icon_url: Option<Option<String>>,
    #[serde(rename = "app_store_icon_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub app_store_icon_url: Option<Option<String>>,
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    /// True while the competitor's historical mentions are being recalculated
    #[serde(rename = "processing", skip_serializing_if = "Option::is_none")]
    pub processing: Option<bool>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl CompetitorDetails {
    pub fn new() -> CompetitorDetails {
        CompetitorDetails {
            id: None,
            project_id: None,
            brand_name: None,
            domain: None,
            matching_names: None,
            google_play_id: None,
            app_store_id: None,
            citation_match_mode: None,
            citation_match_path: None,
            google_play_name: None,
            app_store_name: None,
            google_play_icon_url: None,
            app_store_icon_url: None,
            color: None,
            processing: None,
            created_at: None,
            request_id: None,
        }
    }
}

