/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitorCreateResponseCompetitor {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "brand_name")]
    pub brand_name: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "citation_match_mode")]
    pub citation_match_mode: models::CitationMatchMode,
    /// Set only when citation_match_mode is path_prefix
    #[serde(rename = "citation_match_path", deserialize_with = "Option::deserialize")]
    pub citation_match_path: Option<String>,
    #[serde(rename = "color", deserialize_with = "Option::deserialize")]
    pub color: Option<String>,
    #[serde(rename = "matching_names")]
    pub matching_names: Vec<String>,
}

impl CompetitorCreateResponseCompetitor {
    pub fn new(id: i32, brand_name: String, domain: String, citation_match_mode: models::CitationMatchMode, citation_match_path: Option<String>, color: Option<String>, matching_names: Vec<String>) -> CompetitorCreateResponseCompetitor {
        CompetitorCreateResponseCompetitor {
            id,
            brand_name,
            domain,
            citation_match_mode,
            citation_match_path,
            color,
            matching_names,
        }
    }
}

