/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Competitor {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Bare (scheme-less) domain. Null only on the own-brand row (include_project_brand=true) when the project has no URL.
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    /// Alternative names matched as this competitor. Absent on the own-brand row
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    #[serde(rename = "citation_match_mode", skip_serializing_if = "Option::is_none")]
    pub citation_match_mode: Option<models::CitationMatchMode>,
    /// Set only when citation_match_mode is path_prefix
    #[serde(rename = "citation_match_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub citation_match_path: Option<Option<String>>,
    /// Only present when include_project_brand=true
    #[serde(rename = "actor_type", skip_serializing_if = "Option::is_none")]
    pub actor_type: Option<ActorType>,
    /// Only present when include_project_brand=true
    #[serde(rename = "is_own", skip_serializing_if = "Option::is_none")]
    pub is_own: Option<bool>,
}

impl Competitor {
    pub fn new() -> Competitor {
        Competitor {
            id: None,
            name: None,
            domain: None,
            matching_names: None,
            citation_match_mode: None,
            citation_match_path: None,
            actor_type: None,
            is_own: None,
        }
    }
}
/// Only present when include_project_brand=true
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActorType {
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "competitor")]
    Competitor,
}

impl Default for ActorType {
    fn default() -> ActorType {
        Self::Project
    }
}

