/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompetitorMentionRecord {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "competitor_id")]
    pub competitor_id: i32,
    /// The competitor's brand name
    #[serde(rename = "name")]
    pub name: String,
    /// The competitor's bare domain
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "prompt_execution_id")]
    pub prompt_execution_id: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CompetitorMentionRecord {
    pub fn new(id: i32, competitor_id: i32, name: String, domain: String, prompt_execution_id: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> CompetitorMentionRecord {
        CompetitorMentionRecord {
            id,
            competitor_id,
            name,
            domain,
            prompt_execution_id,
            created_at,
        }
    }
}

