/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectDraftRequest {
    /// Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
    #[serde(rename = "website_url")]
    pub website_url: String,
    #[serde(rename = "main_country")]
    pub main_country: String,
    #[serde(rename = "main_language")]
    pub main_language: String,
    #[serde(rename = "use_subdomain", skip_serializing_if = "Option::is_none")]
    pub use_subdomain: Option<bool>,
    #[serde(rename = "suggest", skip_serializing_if = "Option::is_none")]
    pub suggest: Option<bool>,
    #[serde(rename = "execute_prompts_immediately", skip_serializing_if = "Option::is_none")]
    pub execute_prompts_immediately: Option<bool>,
}

impl CreateProjectDraftRequest {
    pub fn new(website_url: String, main_country: String, main_language: String) -> CreateProjectDraftRequest {
        CreateProjectDraftRequest {
            website_url,
            main_country,
            main_language,
            use_subdomain: None,
            suggest: None,
            execute_prompts_immediately: None,
        }
    }
}

