/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCompetitorRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "brand_name")]
    pub brand_name: String,
    /// URL is accepted and normalised to host (e.g. https://www.openai.com → openai.com)
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    /// domain includes the registrable domain and all subdomains; host requires the exact hostname; path_prefix also requires citation_match_path
    #[serde(rename = "citation_match_mode", skip_serializing_if = "Option::is_none")]
    pub citation_match_mode: Option<CitationMatchMode>,
    /// Required when citation_match_mode=path_prefix, e.g. /es. Case-sensitive; trailing slash is optional; query and fragment are ignored
    #[serde(rename = "citation_match_path", skip_serializing_if = "Option::is_none")]
    pub citation_match_path: Option<String>,
}

impl CreateCompetitorRequest {
    pub fn new(project_id: i32, brand_name: String, domain: String) -> CreateCompetitorRequest {
        CreateCompetitorRequest {
            project_id,
            brand_name,
            domain,
            matching_names: None,
            citation_match_mode: None,
            citation_match_path: None,
        }
    }
}
/// domain includes the registrable domain and all subdomains; host requires the exact hostname; path_prefix also requires citation_match_path
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CitationMatchMode {
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "host")]
    Host,
    #[serde(rename = "path_prefix")]
    PathPrefix,
}

impl Default for CitationMatchMode {
    fn default() -> CitationMatchMode {
        Self::Domain
    }
}

