/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "event_type")]
    pub event_type: EventType,
    /// Public HTTPS URL that will receive signed event payloads
    #[serde(rename = "target_url")]
    pub target_url: String,
}

impl CreateWebhookRequest {
    pub fn new(project_id: i32, event_type: EventType, target_url: String) -> CreateWebhookRequest {
        CreateWebhookRequest {
            project_id,
            event_type,
            target_url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "mention.created")]
    MentionCreated,
    #[serde(rename = "competitor_mention.created")]
    CompetitorMentionCreated,
    #[serde(rename = "citation.created")]
    CitationCreated,
    #[serde(rename = "prompt_execution.completed")]
    PromptExecutionCompleted,
    #[serde(rename = "sentiment.negative_detected")]
    SentimentNegativeDetected,
    #[serde(rename = "recommendation.completed")]
    RecommendationCompleted,
    #[serde(rename = "intelligence_task.completed")]
    IntelligenceTaskCompleted,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::MentionCreated
    }
}

