/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeProjectDraftRequest {
    #[serde(rename = "weekly_email_subscribed", skip_serializing_if = "Option::is_none")]
    pub weekly_email_subscribed: Option<bool>,
    #[serde(rename = "execute_prompts_immediately", skip_serializing_if = "Option::is_none")]
    pub execute_prompts_immediately: Option<bool>,
}

impl FinalizeProjectDraftRequest {
    pub fn new() -> FinalizeProjectDraftRequest {
        FinalizeProjectDraftRequest {
            weekly_email_subscribed: None,
            execute_prompts_immediately: None,
        }
    }
}

