/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAlert {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "audit_id", skip_serializing_if = "Option::is_none")]
    pub audit_id: Option<String>,
    #[serde(rename = "audit_type", skip_serializing_if = "Option::is_none")]
    pub audit_type: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(rename = "run_sequence", skip_serializing_if = "Option::is_none")]
    pub run_sequence: Option<i32>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::GeoAlertEventsInner>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "app_url", skip_serializing_if = "Option::is_none")]
    pub app_url: Option<String>,
}

impl GeoAlert {
    pub fn new() -> GeoAlert {
        GeoAlert {
            id: None,
            audit_id: None,
            audit_type: None,
            target: None,
            run_sequence: None,
            severity: None,
            events: None,
            created_at: None,
            app_url: None,
        }
    }
}

