/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAlertEventsInner {
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    #[serde(rename = "check_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_key: Option<Option<String>>,
    #[serde(rename = "subject_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject_key: Option<Option<String>>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl GeoAlertEventsInner {
    pub fn new() -> GeoAlertEventsInner {
        GeoAlertEventsInner {
            kind: None,
            check_key: None,
            subject_key: None,
            severity: None,
            message: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "new_critical")]
    NewCritical,
    #[serde(rename = "regression")]
    Regression,
    #[serde(rename = "recovered")]
    Recovered,
    #[serde(rename = "score_drop")]
    ScoreDrop,
    #[serde(rename = "unreachable")]
    Unreachable,
    #[serde(rename = "paused")]
    Paused,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::NewCritical
    }
}

