/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditRunResponse {
    /// Run number within the audit, starting at 1
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "trigger", skip_serializing_if = "Option::is_none")]
    pub trigger: Option<Trigger>,
    #[serde(rename = "score", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score: Option<Option<f64>>,
    #[serde(rename = "grade", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub grade: Option<Option<String>>,
    /// Score change against the previous completed run
    #[serde(rename = "score_delta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score_delta: Option<Option<f64>>,
    /// False when the checks or the audit settings changed since the previous run, so a diff may reflect that change
    #[serde(rename = "comparable_to_previous", skip_serializing_if = "Option::is_none")]
    pub comparable_to_previous: Option<bool>,
    #[serde(rename = "new_issues", skip_serializing_if = "Option::is_none")]
    pub new_issues: Option<i32>,
    #[serde(rename = "fixed_issues", skip_serializing_if = "Option::is_none")]
    pub fixed_issues: Option<i32>,
    #[serde(rename = "regressed_issues", skip_serializing_if = "Option::is_none")]
    pub regressed_issues: Option<i32>,
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<String>>,
    #[serde(rename = "engine_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<Option<String>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "finished_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "app_url", skip_serializing_if = "Option::is_none")]
    pub app_url: Option<String>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl GeoAuditRunResponse {
    pub fn new() -> GeoAuditRunResponse {
        GeoAuditRunResponse {
            sequence: None,
            status: None,
            trigger: None,
            score: None,
            grade: None,
            score_delta: None,
            comparable_to_previous: None,
            new_issues: None,
            fixed_issues: None,
            regressed_issues: None,
            error: None,
            engine_version: None,
            created_at: None,
            finished_at: None,
            app_url: None,
            project_id: None,
            request_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "unreachable")]
    Unreachable,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Trigger {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "mcp")]
    Mcp,
    #[serde(rename = "legacy_import")]
    LegacyImport,
}

impl Default for Trigger {
    fn default() -> Trigger {
        Self::Scheduled
    }
}

