/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAudit {
    /// Stable audit id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "audit_type", skip_serializing_if = "Option::is_none")]
    pub audit_type: Option<AuditType>,
    /// The audited domain (site-wide types) or page URL, normalized
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(rename = "country_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<Option<String>>,
    #[serde(rename = "cadence", skip_serializing_if = "Option::is_none")]
    pub cadence: Option<Cadence>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// user, or unreachable when three runs in a row could not reach the site
    #[serde(rename = "paused_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub paused_reason: Option<Option<String>>,
    #[serde(rename = "schedule", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Option<Box<models::GeoAuditSchedule>>>,
    #[serde(rename = "next_run_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_run_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "email_alerts", skip_serializing_if = "Option::is_none")]
    pub email_alerts: Option<bool>,
    /// Whether this audit type can run weekly or monthly
    #[serde(rename = "recurring_available", skip_serializing_if = "Option::is_none")]
    pub recurring_available: Option<bool>,
    /// Whether runs of this type produce findings and issues, or a score only
    #[serde(rename = "checks_tracked", skip_serializing_if = "Option::is_none")]
    pub checks_tracked: Option<bool>,
    #[serde(rename = "latest_run", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latest_run: Option<Option<Box<models::GeoAuditRun>>>,
    #[serde(rename = "open_issues", skip_serializing_if = "Option::is_none")]
    pub open_issues: Option<i32>,
    #[serde(rename = "open_critical_issues", skip_serializing_if = "Option::is_none")]
    pub open_critical_issues: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "app_url", skip_serializing_if = "Option::is_none")]
    pub app_url: Option<String>,
}

impl GeoAudit {
    pub fn new() -> GeoAudit {
        GeoAudit {
            id: None,
            audit_type: None,
            target: None,
            country_code: None,
            cadence: None,
            status: None,
            paused_reason: None,
            schedule: None,
            next_run_at: None,
            email_alerts: None,
            recurring_available: None,
            checks_tracked: None,
            latest_run: None,
            open_issues: None,
            open_critical_issues: None,
            created_at: None,
            app_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuditType {
    #[serde(rename = "agent_readiness")]
    AgentReadiness,
    #[serde(rename = "robots_txt")]
    RobotsTxt,
    #[serde(rename = "crawlability")]
    Crawlability,
    #[serde(rename = "schema")]
    Schema,
    #[serde(rename = "content_readiness")]
    ContentReadiness,
    #[serde(rename = "discoverability")]
    Discoverability,
    #[serde(rename = "site_structure")]
    SiteStructure,
}

impl Default for AuditType {
    fn default() -> AuditType {
        Self::AgentReadiness
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cadence {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "monthly")]
    Monthly,
}

impl Default for Cadence {
    fn default() -> Cadence {
        Self::Once
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

