/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditUpdateRequest {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "cadence", skip_serializing_if = "Option::is_none")]
    pub cadence: Option<Cadence>,
    /// Weekly: 0 (Sunday) to 6. Monthly: 1 to 28.
    #[serde(rename = "schedule_day", skip_serializing_if = "Option::is_none")]
    pub schedule_day: Option<i32>,
    /// Hour of the day, 0 to 23, in the audit time zone
    #[serde(rename = "schedule_hour", skip_serializing_if = "Option::is_none")]
    pub schedule_hour: Option<i32>,
    /// paused stops scheduled runs, active resumes them, archived is the same as DELETE
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "email_alerts", skip_serializing_if = "Option::is_none")]
    pub email_alerts: Option<bool>,
}

impl GeoAuditUpdateRequest {
    pub fn new() -> GeoAuditUpdateRequest {
        GeoAuditUpdateRequest {
            project_id: None,
            cadence: None,
            schedule_day: None,
            schedule_hour: None,
            status: None,
            email_alerts: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cadence {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "weekly")]
    Weekly,
    #[serde(rename = "monthly")]
    Monthly,
}

impl Default for Cadence {
    fn default() -> Cadence {
        Self::Once
    }
}
/// paused stops scheduled runs, active resumes them, archived is the same as DELETE
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "archived")]
    Archived,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

