/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditFinding {
    /// Stable key of the check within its audit type
    #[serde(rename = "check_key", skip_serializing_if = "Option::is_none")]
    pub check_key: Option<String>,
    #[serde(rename = "check_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_title: Option<Option<String>>,
    /// What the check is about (site for site-wide checks, a bot slug for robots.txt bot checks)
    #[serde(rename = "subject_key", skip_serializing_if = "Option::is_none")]
    pub subject_key: Option<String>,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<Severity>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<serde_json::Value>,
}

impl GeoAuditFinding {
    pub fn new() -> GeoAuditFinding {
        GeoAuditFinding {
            check_key: None,
            check_title: None,
            subject_key: None,
            subject: None,
            status: None,
            severity: None,
            evidence: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pass")]
    Pass,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "fail")]
    Fail,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "not_applicable")]
    NotApplicable,
    #[serde(rename = "unknown")]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pass
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Severity {
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "info")]
    Info,
}

impl Default for Severity {
    fn default() -> Severity {
        Self::Critical
    }
}

