/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditIssue {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "check_key", skip_serializing_if = "Option::is_none")]
    pub check_key: Option<String>,
    #[serde(rename = "check_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_title: Option<Option<String>>,
    #[serde(rename = "subject_key", skip_serializing_if = "Option::is_none")]
    pub subject_key: Option<String>,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// How the latest comparable run moved the issue
    #[serde(rename = "badge", skip_serializing_if = "Option::is_none")]
    pub badge: Option<Badge>,
    #[serde(rename = "accepted", skip_serializing_if = "Option::is_none")]
    pub accepted: Option<bool>,
    #[serde(rename = "accepted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accepted_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "regression_count", skip_serializing_if = "Option::is_none")]
    pub regression_count: Option<i32>,
    #[serde(rename = "evidence", skip_serializing_if = "Option::is_none")]
    pub evidence: Option<serde_json::Value>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GeoAuditIssue {
    pub fn new() -> GeoAuditIssue {
        GeoAuditIssue {
            id: None,
            check_key: None,
            check_title: None,
            subject_key: None,
            subject: None,
            severity: None,
            state: None,
            badge: None,
            accepted: None,
            accepted_at: None,
            regression_count: None,
            evidence: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "gone")]
    Gone,
}

impl Default for State {
    fn default() -> State {
        Self::Open
    }
}
/// How the latest comparable run moved the issue
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Badge {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "persisting")]
    Persisting,
    #[serde(rename = "regressed")]
    Regressed,
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "gone")]
    Gone,
}

impl Default for Badge {
    fn default() -> Badge {
        Self::New
    }
}

