/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GeoAuditSchedule : Present for weekly and monthly audits. day is 0 (Sunday) to 6 for weekly audits and 1 to 28 for monthly ones; hour is in timezone.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditSchedule {
    #[serde(rename = "day", skip_serializing_if = "Option::is_none")]
    pub day: Option<i32>,
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<i32>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
}

impl GeoAuditSchedule {
    /// Present for weekly and monthly audits. day is 0 (Sunday) to 6 for weekly audits and 1 to 28 for monthly ones; hour is in timezone.
    pub fn new() -> GeoAuditSchedule {
        GeoAuditSchedule {
            day: None,
            hour: None,
            timezone: None,
        }
    }
}

