/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditComparisonChangesInner {
    #[serde(rename = "check_key", skip_serializing_if = "Option::is_none")]
    pub check_key: Option<String>,
    #[serde(rename = "check_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_title: Option<Option<String>>,
    #[serde(rename = "subject_key", skip_serializing_if = "Option::is_none")]
    pub subject_key: Option<String>,
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    #[serde(rename = "severity", skip_serializing_if = "Option::is_none")]
    pub severity: Option<String>,
    #[serde(rename = "from_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_status: Option<Option<String>>,
    #[serde(rename = "to_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to_status: Option<Option<String>>,
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<Change>,
}

impl GeoAuditComparisonChangesInner {
    pub fn new() -> GeoAuditComparisonChangesInner {
        GeoAuditComparisonChangesInner {
            check_key: None,
            check_title: None,
            subject_key: None,
            subject: None,
            severity: None,
            from_status: None,
            to_status: None,
            change: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Change {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "changed")]
    Changed,
    #[serde(rename = "appeared")]
    Appeared,
    #[serde(rename = "disappeared")]
    Disappeared,
    #[serde(rename = "unchanged")]
    Unchanged,
}

impl Default for Change {
    fn default() -> Change {
        Self::New
    }
}

