/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoAuditComparison {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "from_run", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from_run: Option<Option<Box<models::GeoAuditRun>>>,
    #[serde(rename = "to_run", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to_run: Option<Option<Box<models::GeoAuditRun>>>,
    #[serde(rename = "comparable", skip_serializing_if = "Option::is_none")]
    pub comparable: Option<bool>,
    #[serde(rename = "score_delta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub score_delta: Option<Option<f64>>,
    #[serde(rename = "metric_deltas", skip_serializing_if = "Option::is_none")]
    pub metric_deltas: Option<std::collections::HashMap<String, f64>>,
    #[serde(rename = "counts", skip_serializing_if = "Option::is_none")]
    pub counts: Option<std::collections::HashMap<String, i32>>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<models::GeoAuditComparisonChangesInner>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl GeoAuditComparison {
    pub fn new() -> GeoAuditComparison {
        GeoAuditComparison {
            project_id: None,
            from_run: None,
            to_run: None,
            comparable: None,
            score_delta: None,
            metric_deltas: None,
            counts: None,
            changes: None,
            request_id: None,
        }
    }
}

