/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccount200ResponseLimits {
    #[serde(rename = "prompts", skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Box<models::AccountQuota>>,
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Box<models::AccountQuota>>,
    #[serde(rename = "competitors_per_project", skip_serializing_if = "Option::is_none")]
    pub competitors_per_project: Option<Box<models::AccountCapacity>>,
    #[serde(rename = "intelligence_tasks", skip_serializing_if = "Option::is_none")]
    pub intelligence_tasks: Option<Box<models::AccountQuota>>,
    #[serde(rename = "team_members", skip_serializing_if = "Option::is_none")]
    pub team_members: Option<Box<models::AccountCapacity>>,
    #[serde(rename = "recurring_geo_audits", skip_serializing_if = "Option::is_none")]
    pub recurring_geo_audits: Option<Box<models::AccountQuota>>,
    #[serde(rename = "geo_audit_manual_runs", skip_serializing_if = "Option::is_none")]
    pub geo_audit_manual_runs: Option<Box<models::AccountQuota>>,
}

impl GetAccount200ResponseLimits {
    pub fn new() -> GetAccount200ResponseLimits {
        GetAccount200ResponseLimits {
            prompts: None,
            projects: None,
            competitors_per_project: None,
            intelligence_tasks: None,
            team_members: None,
            recurring_geo_audits: None,
            geo_audit_manual_runs: None,
        }
    }
}

