/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetTimeseriesCollectionIdParameter {
    Integer(i32),
    String(String),
}

impl Default for GetTimeseriesCollectionIdParameter {
    fn default() -> Self {
        Self::Integer(Default::default())
    }
}

