/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntelligenceTaskCreateRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// product_listing is API-only: it needs product and returns ready-to-apply product page copy
    #[serde(rename = "task_type")]
    pub task_type: TaskType,
    /// Not used by product_listing; send null or omit it
    #[serde(rename = "prompt_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt_id: Option<Option<i32>>,
    #[serde(rename = "custom_topic", skip_serializing_if = "Option::is_none")]
    pub custom_topic: Option<String>,
    #[serde(rename = "user_instructions", skip_serializing_if = "Option::is_none")]
    pub user_instructions: Option<String>,
    #[serde(rename = "output_language_code", skip_serializing_if = "Option::is_none")]
    pub output_language_code: Option<String>,
    #[serde(rename = "existing_content", skip_serializing_if = "Option::is_none")]
    pub existing_content: Option<String>,
    #[serde(rename = "existing_content_url", skip_serializing_if = "Option::is_none")]
    pub existing_content_url: Option<String>,
    #[serde(rename = "product", skip_serializing_if = "Option::is_none")]
    pub product: Option<Box<models::IntelligenceTaskProduct>>,
    /// product_listing only: up to 20 project prompts the copy should answer
    #[serde(rename = "prompt_ids", skip_serializing_if = "Option::is_none")]
    pub prompt_ids: Option<Vec<i32>>,
}

impl IntelligenceTaskCreateRequest {
    pub fn new(project_id: i32, task_type: TaskType) -> IntelligenceTaskCreateRequest {
        IntelligenceTaskCreateRequest {
            project_id,
            task_type,
            prompt_id: None,
            custom_topic: None,
            user_instructions: None,
            output_language_code: None,
            existing_content: None,
            existing_content_url: None,
            product: None,
            prompt_ids: None,
        }
    }
}
/// product_listing is API-only: it needs product and returns ready-to-apply product page copy
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskType {
    #[serde(rename = "brief")]
    Brief,
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "pr_insights")]
    PrInsights,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "product_listing")]
    ProductListing,
}

impl Default for TaskType {
    fn default() -> TaskType {
        Self::Brief
    }
}

