/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntelligenceTaskCreateRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "task_type")]
    pub task_type: TaskType,
    #[serde(rename = "prompt_id", skip_serializing_if = "Option::is_none")]
    pub prompt_id: Option<i32>,
    #[serde(rename = "custom_topic", skip_serializing_if = "Option::is_none")]
    pub custom_topic: Option<String>,
    #[serde(rename = "user_instructions", skip_serializing_if = "Option::is_none")]
    pub user_instructions: Option<String>,
    #[serde(rename = "output_language_code", skip_serializing_if = "Option::is_none")]
    pub output_language_code: Option<String>,
    #[serde(rename = "existing_content", skip_serializing_if = "Option::is_none")]
    pub existing_content: Option<String>,
    #[serde(rename = "existing_content_url", skip_serializing_if = "Option::is_none")]
    pub existing_content_url: Option<String>,
}

impl IntelligenceTaskCreateRequest {
    pub fn new(project_id: i32, task_type: TaskType) -> IntelligenceTaskCreateRequest {
        IntelligenceTaskCreateRequest {
            project_id,
            task_type,
            prompt_id: None,
            custom_topic: None,
            user_instructions: None,
            output_language_code: None,
            existing_content: None,
            existing_content_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskType {
    #[serde(rename = "brief")]
    Brief,
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "pr_insights")]
    PrInsights,
    #[serde(rename = "custom")]
    Custom,
}

impl Default for TaskType {
    fn default() -> TaskType {
        Self::Brief
    }
}

