/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntelligenceTaskUpdateRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// Dotted result_data paths (title, sections.0.content, key_points.2) mapped to their replacement text. Only string fields that already exist are editable; sections cannot be added or removed.
    #[serde(rename = "edits")]
    pub edits: std::collections::HashMap<String, String>,
}

impl IntelligenceTaskUpdateRequest {
    pub fn new(project_id: i32, edits: std::collections::HashMap<String, String>) -> IntelligenceTaskUpdateRequest {
        IntelligenceTaskUpdateRequest {
            project_id,
            edits,
        }
    }
}

