/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntelligenceTaskProductImagesInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "alt", skip_serializing_if = "Option::is_none")]
    pub alt: Option<String>,
}

impl IntelligenceTaskProductImagesInner {
    pub fn new(id: String) -> IntelligenceTaskProductImagesInner {
        IntelligenceTaskProductImagesInner {
            id,
            alt: None,
        }
    }
}

