/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntelligenceTaskProduct : The store product a product_listing task rewrites
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntelligenceTaskProduct {
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description_html", skip_serializing_if = "Option::is_none")]
    pub description_html: Option<String>,
    #[serde(rename = "seo_title", skip_serializing_if = "Option::is_none")]
    pub seo_title: Option<String>,
    #[serde(rename = "seo_description", skip_serializing_if = "Option::is_none")]
    pub seo_description: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "product_type", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<String>,
    #[serde(rename = "images", skip_serializing_if = "Option::is_none")]
    pub images: Option<Vec<models::IntelligenceTaskProductImagesInner>>,
}

impl IntelligenceTaskProduct {
    /// The store product a product_listing task rewrites
    pub fn new(title: String) -> IntelligenceTaskProduct {
        IntelligenceTaskProduct {
            external_id: None,
            title,
            description_html: None,
            seo_title: None,
            seo_description: None,
            url: None,
            product_type: None,
            images: None,
        }
    }
}

