/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCompetitors200Response {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "competitors", skip_serializing_if = "Option::is_none")]
    pub competitors: Option<Vec<models::Competitor>>,
}

impl ListCompetitors200Response {
    pub fn new() -> ListCompetitors200Response {
        ListCompetitors200Response {
            project_id: None,
            competitors: None,
        }
    }
}

