/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProjects200Response {
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::Project>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl ListProjects200Response {
    pub fn new() -> ListProjects200Response {
        ListProjects200Response {
            projects: None,
            request_id: None,
        }
    }
}

