/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWebhooks200ResponseDataInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<EventType>,
    #[serde(rename = "target_url", skip_serializing_if = "Option::is_none")]
    pub target_url: Option<String>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "failure_count", skip_serializing_if = "Option::is_none")]
    pub failure_count: Option<i32>,
    #[serde(rename = "last_delivered_at", skip_serializing_if = "Option::is_none")]
    pub last_delivered_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ListWebhooks200ResponseDataInner {
    pub fn new() -> ListWebhooks200ResponseDataInner {
        ListWebhooks200ResponseDataInner {
            id: None,
            project_id: None,
            event_type: None,
            target_url: None,
            disabled: None,
            failure_count: None,
            last_delivered_at: None,
            created_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "mention.created")]
    MentionCreated,
    #[serde(rename = "competitor_mention.created")]
    CompetitorMentionCreated,
    #[serde(rename = "citation.created")]
    CitationCreated,
    #[serde(rename = "prompt_execution.completed")]
    PromptExecutionCompleted,
    #[serde(rename = "sentiment.negative_detected")]
    SentimentNegativeDetected,
    #[serde(rename = "recommendation.completed")]
    RecommendationCompleted,
    #[serde(rename = "intelligence_task.completed")]
    IntelligenceTaskCompleted,
    #[serde(rename = "intelligence_task.updated")]
    IntelligenceTaskUpdated,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::MentionCreated
    }
}

