/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalBusinessesTotals {
    #[serde(rename = "businesses", skip_serializing_if = "Option::is_none")]
    pub businesses: Option<i32>,
    #[serde(rename = "your_businesses", skip_serializing_if = "Option::is_none")]
    pub your_businesses: Option<i32>,
    #[serde(rename = "appearances", skip_serializing_if = "Option::is_none")]
    pub appearances: Option<i32>,
    #[serde(rename = "avg_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avg_rating: Option<Option<f64>>,
    #[serde(rename = "executions_with_local_businesses", skip_serializing_if = "Option::is_none")]
    pub executions_with_local_businesses: Option<i32>,
}

impl LocalBusinessesTotals {
    pub fn new() -> LocalBusinessesTotals {
        LocalBusinessesTotals {
            businesses: None,
            your_businesses: None,
            appearances: None,
            avg_rating: None,
            executions_with_local_businesses: None,
        }
    }
}

