/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalesResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// Country codes with data
    #[serde(rename = "countries")]
    pub countries: Vec<String>,
    /// Language codes with data
    #[serde(rename = "languages")]
    pub languages: Vec<String>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl LocalesResponse {
    pub fn new(project_id: i32, countries: Vec<String>, languages: Vec<String>, request_id: String) -> LocalesResponse {
        LocalesResponse {
            project_id,
            countries,
            languages,
            request_id,
        }
    }
}

