/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalBusiness {
    /// Stable grouping key: the lowercased name and address
    #[serde(rename = "business_key", skip_serializing_if = "Option::is_none")]
    pub business_key: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<String>>,
    #[serde(rename = "domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Option<String>>,
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "avg_rating", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avg_rating: Option<Option<f64>>,
    #[serde(rename = "reviews", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reviews: Option<Option<i32>>,
    /// Average rank of the business in the answer's list (1 = first)
    #[serde(rename = "avg_position", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avg_position: Option<Option<f64>>,
    #[serde(rename = "prompts", skip_serializing_if = "Option::is_none")]
    pub prompts: Option<i32>,
    #[serde(rename = "appearances", skip_serializing_if = "Option::is_none")]
    pub appearances: Option<i32>,
    #[serde(rename = "is_client", skip_serializing_if = "Option::is_none")]
    pub is_client: Option<bool>,
    #[serde(rename = "competitor_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub competitor_id: Option<Option<i32>>,
    #[serde(rename = "competitor_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub competitor_name: Option<Option<String>>,
}

impl LocalBusiness {
    pub fn new() -> LocalBusiness {
        LocalBusiness {
            business_key: None,
            title: None,
            address: None,
            domain: None,
            url: None,
            phone: None,
            avg_rating: None,
            reviews: None,
            avg_position: None,
            prompts: None,
            appearances: None,
            is_client: None,
            competitor_id: None,
            competitor_name: None,
        }
    }
}

