/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionsResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
    /// Rows matching the filters across every page
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "request_id")]
    pub request_id: String,
    #[serde(rename = "data")]
    pub data: Vec<models::MentionRecord>,
}

impl MentionsResponse {
    pub fn new(project_id: i32, page: i32, per_page: i32, total: i32, request_id: String, data: Vec<models::MentionRecord>) -> MentionsResponse {
        MentionsResponse {
            project_id,
            page,
            per_page,
            total,
            request_id,
            data,
        }
    }
}

