/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionRecord {
    #[serde(rename = "id")]
    pub id: i32,
    /// The project's brand name (its name when no brand name is set)
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "prompt_id")]
    pub prompt_id: i32,
    #[serde(rename = "prompt_execution_id")]
    pub prompt_execution_id: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl MentionRecord {
    pub fn new(id: i32, name: String, prompt_id: i32, prompt_execution_id: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> MentionRecord {
        MentionRecord {
            id,
            name,
            prompt_id,
            prompt_execution_id,
            created_at,
        }
    }
}

