/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsFiltersEcho : The filters the response was computed with, as the server resolved them. Each endpoint echoes only the keys it reads; a filter that was not given comes back null (or an empty list).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetricsFiltersEcho {
    /// Requested metrics after alias resolution (mention_rate is echoed as visibility)
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<String>>,
    /// day, week or month
    #[serde(rename = "granularity", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<String>,
    /// The model filter, or null when absent or not enabled for the account
    #[serde(rename = "model", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    /// The collection_id parameter as sent (one id or a comma-separated list)
    #[serde(rename = "collection_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collection_id: Option<Option<String>>,
    #[serde(rename = "collection_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collection_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "domains", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domains: Option<Option<Vec<String>>>,
    /// Comma-separated country codes
    #[serde(rename = "country_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<Option<String>>,
    /// Comma-separated language codes
    #[serde(rename = "language_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_code: Option<Option<String>>,
    /// The prompt id filter
    #[serde(rename = "prompt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<Option<i32>>,
    /// Comma-separated prompt types
    #[serde(rename = "prompt_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompt_type: Option<Option<String>>,
    #[serde(rename = "brand_kind", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand_kind: Option<Option<String>>,
    /// Competitor ids from the competitors parameter; empty when it was not given
    #[serde(rename = "competitors", skip_serializing_if = "Option::is_none")]
    pub competitors: Option<Vec<i32>>,
    #[serde(rename = "include_project", skip_serializing_if = "Option::is_none")]
    pub include_project: Option<bool>,
    /// Only present when a query filter was given
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

impl MetricsFiltersEcho {
    /// The filters the response was computed with, as the server resolved them. Each endpoint echoes only the keys it reads; a filter that was not given comes back null (or an empty list).
    pub fn new() -> MetricsFiltersEcho {
        MetricsFiltersEcho {
            metrics: None,
            granularity: None,
            model: None,
            collection_id: None,
            collection_ids: None,
            domains: None,
            country_code: None,
            language_code: None,
            prompt: None,
            prompt_type: None,
            brand_kind: None,
            competitors: None,
            include_project: None,
            query: None,
        }
    }
}

