/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaginatedEnvelope : Envelope shared by the paginated listings; each listing adds its own data rows
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedEnvelope {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "per_page")]
    pub per_page: i32,
    /// Rows matching the filters across every page
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl PaginatedEnvelope {
    /// Envelope shared by the paginated listings; each listing adds its own data rows
    pub fn new(project_id: i32, page: i32, per_page: i32, total: i32, request_id: String) -> PaginatedEnvelope {
        PaginatedEnvelope {
            project_id,
            page,
            per_page,
            total,
            request_id,
        }
    }
}

