/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectDetailsAllOfDataCoverage : AI models, countries and languages the project has data for
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectDetailsAllOfDataCoverage {
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<Vec<Models>>,
    #[serde(rename = "countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<Vec<String>>,
    #[serde(rename = "languages", skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<String>>,
}

impl ProjectDetailsAllOfDataCoverage {
    /// AI models, countries and languages the project has data for
    pub fn new() -> ProjectDetailsAllOfDataCoverage {
        ProjectDetailsAllOfDataCoverage {
            models: None,
            countries: None,
            languages: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Models {
    #[serde(rename = "chatgpt")]
    Chatgpt,
    #[serde(rename = "perplexity")]
    Perplexity,
    #[serde(rename = "ai_mode")]
    AiMode,
    #[serde(rename = "ai_overview")]
    AiOverview,
    #[serde(rename = "gemini")]
    Gemini,
    #[serde(rename = "copilot")]
    Copilot,
    #[serde(rename = "amazon_rufus")]
    AmazonRufus,
    #[serde(rename = "claude")]
    Claude,
    #[serde(rename = "grok")]
    Grok,
    #[serde(rename = "deepseek")]
    Deepseek,
    #[serde(rename = "naver_ai")]
    NaverAi,
    #[serde(rename = "baidu_ai")]
    BaiduAi,
    #[serde(rename = "meta_ai")]
    MetaAi,
}

impl Default for Models {
    fn default() -> Models {
        Self::Chatgpt
    }
}

