/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectCreateRequestOwnedMedia : Requires Growth plan or above
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateRequestOwnedMedia {
    #[serde(rename = "youtube_channel_url", skip_serializing_if = "Option::is_none")]
    pub youtube_channel_url: Option<String>,
    #[serde(rename = "instagram_profile_url", skip_serializing_if = "Option::is_none")]
    pub instagram_profile_url: Option<String>,
    #[serde(rename = "facebook_page_url", skip_serializing_if = "Option::is_none")]
    pub facebook_page_url: Option<String>,
    #[serde(rename = "tiktok_profile_url", skip_serializing_if = "Option::is_none")]
    pub tiktok_profile_url: Option<String>,
    #[serde(rename = "app_store_url", skip_serializing_if = "Option::is_none")]
    pub app_store_url: Option<String>,
    #[serde(rename = "google_play_url", skip_serializing_if = "Option::is_none")]
    pub google_play_url: Option<String>,
}

impl ProjectCreateRequestOwnedMedia {
    /// Requires Growth plan or above
    pub fn new() -> ProjectCreateRequestOwnedMedia {
        ProjectCreateRequestOwnedMedia {
            youtube_channel_url: None,
            instagram_profile_url: None,
            facebook_page_url: None,
            tiktok_profile_url: None,
            app_store_url: None,
            google_play_url: None,
        }
    }
}

