/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectDetailsAllOfStatsPromptsByBrandKind : Prompt counts per brand focus
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectDetailsAllOfStatsPromptsByBrandKind {
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<i32>,
    #[serde(rename = "brand_other", skip_serializing_if = "Option::is_none")]
    pub brand_other: Option<i32>,
    #[serde(rename = "non_brand", skip_serializing_if = "Option::is_none")]
    pub non_brand: Option<i32>,
}

impl ProjectDetailsAllOfStatsPromptsByBrandKind {
    /// Prompt counts per brand focus
    pub fn new() -> ProjectDetailsAllOfStatsPromptsByBrandKind {
        ProjectDetailsAllOfStatsPromptsByBrandKind {
            brand: None,
            brand_other: None,
            non_brand: None,
        }
    }
}

