/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Internal project label (sidebar, settings, admin)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// LLM-facing brand label (used in prompts and customer-facing charts). Defaults to `name` when not set.
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
}

impl Project {
    pub fn new() -> Project {
        Project {
            id: None,
            name: None,
            brand_name: None,
        }
    }
}

