/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponseEmailSubscription {
    #[serde(rename = "weekly_email_subscribed", skip_serializing_if = "Option::is_none")]
    pub weekly_email_subscribed: Option<bool>,
}

impl ProjectCreateResponseEmailSubscription {
    pub fn new() -> ProjectCreateResponseEmailSubscription {
        ProjectCreateResponseEmailSubscription {
            weekly_email_subscribed: None,
        }
    }
}

