/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponse {
    /// Same shape as GET /dimensions/projects/{id}
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<serde_json::Value>,
    #[serde(rename = "prompts", skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Box<models::ProjectCreateResponsePrompts>>,
    #[serde(rename = "competitors", skip_serializing_if = "Option::is_none")]
    pub competitors: Option<Box<models::ProjectCreateResponseCompetitors>>,
    #[serde(rename = "email_subscription", skip_serializing_if = "Option::is_none")]
    pub email_subscription: Option<Box<models::ProjectCreateResponseEmailSubscription>>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::ProjectCreateResponseLimits>>,
    /// Present and true only on external_identifier replays
    #[serde(rename = "idempotent", skip_serializing_if = "Option::is_none")]
    pub idempotent: Option<bool>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl ProjectCreateResponse {
    pub fn new() -> ProjectCreateResponse {
        ProjectCreateResponse {
            project: None,
            prompts: None,
            competitors: None,
            email_subscription: None,
            limits: None,
            idempotent: None,
            request_id: None,
        }
    }
}

