/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponsePrompts {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<i32>,
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Execution>,
}

impl ProjectCreateResponsePrompts {
    pub fn new() -> ProjectCreateResponsePrompts {
        ProjectCreateResponsePrompts {
            created: None,
            skipped: None,
            execution: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Execution {
    #[serde(rename = "immediate")]
    Immediate,
    #[serde(rename = "deferred_to_next_scheduled_run")]
    DeferredToNextScheduledRun,
}

impl Default for Execution {
    fn default() -> Execution {
        Self::Immediate
    }
}

