/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectDetailsAllOfStats {
    #[serde(rename = "prompts_count", skip_serializing_if = "Option::is_none")]
    pub prompts_count: Option<i32>,
    #[serde(rename = "competitors_count", skip_serializing_if = "Option::is_none")]
    pub competitors_count: Option<i32>,
    #[serde(rename = "collections_count", skip_serializing_if = "Option::is_none")]
    pub collections_count: Option<i32>,
}

impl ProjectDetailsAllOfStats {
    pub fn new() -> ProjectDetailsAllOfStats {
        ProjectDetailsAllOfStats {
            prompts_count: None,
            competitors_count: None,
            collections_count: None,
        }
    }
}

