/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponseLimits {
    #[serde(rename = "projects_remaining", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub projects_remaining: Option<Option<i32>>,
    #[serde(rename = "prompts_available", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prompts_available: Option<Option<i32>>,
    #[serde(rename = "competitors_remaining", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub competitors_remaining: Option<Option<i32>>,
}

impl ProjectCreateResponseLimits {
    pub fn new() -> ProjectCreateResponseLimits {
        ProjectCreateResponseLimits {
            projects_remaining: None,
            prompts_available: None,
            competitors_remaining: None,
        }
    }
}

