/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateResponseCollectionsInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "prompts_attached", skip_serializing_if = "Option::is_none")]
    pub prompts_attached: Option<i32>,
}

impl ProjectCreateResponseCollectionsInner {
    pub fn new() -> ProjectCreateResponseCollectionsInner {
        ProjectCreateResponseCollectionsInner {
            id: None,
            name: None,
            prompts_attached: None,
        }
    }
}

