/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateRequest {
    /// Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
    #[serde(rename = "website_url")]
    pub website_url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "main_country")]
    pub main_country: String,
    #[serde(rename = "main_language")]
    pub main_language: String,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<Vec<String>>,
    /// Business model key (e.g. B2B_SAAS, MARKETPLACE); unknown keys are rejected
    #[serde(rename = "business_model", skip_serializing_if = "Option::is_none")]
    pub business_model: Option<String>,
    /// Free-text business model, only accepted when business_model is OTHER; rejected against any other key
    #[serde(rename = "business_model_other", skip_serializing_if = "Option::is_none")]
    pub business_model_other: Option<String>,
    /// Who the brand sells to. Context for Recommendations and GEO Writer (Brand Book)
    #[serde(rename = "target_audience", skip_serializing_if = "Option::is_none")]
    pub target_audience: Option<String>,
    /// Tone of voice guidance for generated content (Brand Book)
    #[serde(rename = "brand_voice", skip_serializing_if = "Option::is_none")]
    pub brand_voice: Option<String>,
    /// What the brand wants to achieve. Context for GEO Writer and prompt suggestions
    #[serde(rename = "goals", skip_serializing_if = "Option::is_none")]
    pub goals: Option<String>,
    /// Main products or services
    #[serde(rename = "primary_products", skip_serializing_if = "Option::is_none")]
    pub primary_products: Option<Vec<String>>,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    #[serde(rename = "prompts", skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Vec<String>>,
    #[serde(rename = "competitors", skip_serializing_if = "Option::is_none")]
    pub competitors: Option<Vec<models::ProjectCreateRequestCompetitorsInner>>,
    #[serde(rename = "owned_media", skip_serializing_if = "Option::is_none")]
    pub owned_media: Option<Box<models::ProjectCreateRequestOwnedMedia>>,
    #[serde(rename = "use_subdomain", skip_serializing_if = "Option::is_none")]
    pub use_subdomain: Option<bool>,
    #[serde(rename = "weekly_email_subscribed", skip_serializing_if = "Option::is_none")]
    pub weekly_email_subscribed: Option<bool>,
    /// Embed-enabled (Enterprise) accounts only; other accounts receive ERR_PLAN_REQUIRED. Idempotency key and embed-session join key, unique per account
    #[serde(rename = "external_identifier", skip_serializing_if = "Option::is_none")]
    pub external_identifier: Option<String>,
    #[serde(rename = "execute_prompts_immediately", skip_serializing_if = "Option::is_none")]
    pub execute_prompts_immediately: Option<bool>,
}

impl ProjectCreateRequest {
    pub fn new(website_url: String, name: String, main_country: String, main_language: String) -> ProjectCreateRequest {
        ProjectCreateRequest {
            website_url,
            name,
            main_country,
            main_language,
            brand_name: None,
            description: None,
            industry: None,
            business_model: None,
            business_model_other: None,
            target_audience: None,
            brand_voice: None,
            goals: None,
            primary_products: None,
            matching_names: None,
            prompts: None,
            competitors: None,
            owned_media: None,
            use_subdomain: None,
            weekly_email_subscribed: None,
            external_identifier: None,
            execute_prompts_immediately: None,
        }
    }
}

