/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectCreateRequestCompetitorsInner {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
}

impl ProjectCreateRequestCompetitorsInner {
    pub fn new(domain: String) -> ProjectCreateRequestCompetitorsInner {
        ProjectCreateRequestCompetitorsInner {
            domain,
            brand_name: None,
            matching_names: None,
        }
    }
}

