/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptExecutionRecord {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "prompt_id")]
    pub prompt_id: i32,
    /// Null while the answer is still pending
    #[serde(rename = "executed_at", deserialize_with = "Option::deserialize")]
    pub executed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "duration_ms", deserialize_with = "Option::deserialize")]
    pub duration_ms: Option<f64>,
    /// Null while the answer is still pending
    #[serde(rename = "success", deserialize_with = "Option::deserialize")]
    pub success: Option<bool>,
    #[serde(rename = "model")]
    pub model: Model,
    /// Sub-queries the model issued while answering; null when the model reports none
    #[serde(rename = "fan_out_queries", deserialize_with = "Option::deserialize")]
    pub fan_out_queries: Option<Vec<String>>,
    #[serde(rename = "has_mention")]
    pub has_mention: bool,
    #[serde(rename = "has_citation")]
    pub has_citation: bool,
    /// 1 when the answer mentions the brand, otherwise 0
    #[serde(rename = "mentions_count")]
    pub mentions_count: i32,
    /// 1 when the answer cites the brand, otherwise 0
    #[serde(rename = "citations_count")]
    pub citations_count: i32,
    /// Opens this answer in the app. The link names its project, so it opens there for any user with access to that project
    #[serde(rename = "app_url")]
    pub app_url: String,
}

impl PromptExecutionRecord {
    pub fn new(id: i32, prompt_id: i32, executed_at: Option<chrono::DateTime<chrono::FixedOffset>>, duration_ms: Option<f64>, success: Option<bool>, model: Model, fan_out_queries: Option<Vec<String>>, has_mention: bool, has_citation: bool, mentions_count: i32, citations_count: i32, app_url: String) -> PromptExecutionRecord {
        PromptExecutionRecord {
            id,
            prompt_id,
            executed_at,
            duration_ms,
            success,
            model,
            fan_out_queries,
            has_mention,
            has_citation,
            mentions_count,
            citations_count,
            app_url,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Model {
    #[serde(rename = "chatgpt")]
    Chatgpt,
    #[serde(rename = "perplexity")]
    Perplexity,
    #[serde(rename = "ai_mode")]
    AiMode,
    #[serde(rename = "ai_overview")]
    AiOverview,
    #[serde(rename = "gemini")]
    Gemini,
    #[serde(rename = "copilot")]
    Copilot,
    #[serde(rename = "amazon_rufus")]
    AmazonRufus,
    #[serde(rename = "claude")]
    Claude,
    #[serde(rename = "grok")]
    Grok,
    #[serde(rename = "deepseek")]
    Deepseek,
    #[serde(rename = "naver_ai")]
    NaverAi,
    #[serde(rename = "baidu_ai")]
    BaiduAi,
    #[serde(rename = "meta_ai")]
    MetaAi,
}

impl Default for Model {
    fn default() -> Model {
        Self::Chatgpt
    }
}

