/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptsCreateRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "prompts")]
    pub prompts: Vec<String>,
    #[serde(rename = "country_code")]
    pub country_code: String,
    #[serde(rename = "language_code")]
    pub language_code: String,
}

impl PromptsCreateRequest {
    pub fn new(project_id: i32, prompts: Vec<String>, country_code: String, language_code: String) -> PromptsCreateRequest {
        PromptsCreateRequest {
            project_id,
            prompts,
            country_code,
            language_code,
        }
    }
}

