/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptsCreateResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i32>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<i32>,
    #[serde(rename = "total_after", skip_serializing_if = "Option::is_none")]
    pub total_after: Option<i32>,
    #[serde(rename = "prompts_available", skip_serializing_if = "Option::is_none")]
    pub prompts_available: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::PromptsCreateResponseDataInner>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl PromptsCreateResponse {
    pub fn new() -> PromptsCreateResponse {
        PromptsCreateResponse {
            project_id: None,
            created: None,
            skipped: None,
            total_after: None,
            prompts_available: None,
            data: None,
            request_id: None,
        }
    }
}

