/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptSummaryResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<serde_json::Value>,
    #[serde(rename = "breakdown", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<Option<String>>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    #[serde(rename = "sort_dir", skip_serializing_if = "Option::is_none")]
    pub sort_dir: Option<String>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    #[serde(rename = "per_page", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::PromptSummaryRow>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl PromptSummaryResponse {
    pub fn new() -> PromptSummaryResponse {
        PromptSummaryResponse {
            project_id: None,
            from: None,
            to: None,
            filters: None,
            breakdown: None,
            sort: None,
            sort_dir: None,
            page: None,
            per_page: None,
            total: None,
            data: None,
            request_id: None,
        }
    }
}

