/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptRecord {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "prompt_text")]
    pub prompt_text: String,
    /// Primary tag, when the prompt has one
    #[serde(rename = "collection_id", deserialize_with = "Option::deserialize")]
    pub collection_id: Option<i32>,
    /// Every tag the prompt belongs to
    #[serde(rename = "collection_ids")]
    pub collection_ids: Vec<i32>,
    #[serde(rename = "tags")]
    pub tags: Vec<models::TagRef>,
    #[serde(rename = "country_code", deserialize_with = "Option::deserialize")]
    pub country_code: Option<String>,
    #[serde(rename = "language_code", deserialize_with = "Option::deserialize")]
    pub language_code: Option<String>,
    /// Search intent: informational, navigational, commercial or transactional. Null until the prompt is classified
    #[serde(rename = "prompt_type", deserialize_with = "Option::deserialize")]
    pub prompt_type: Option<String>,
    /// Brand focus: brand, brand_other or non_brand. Null until the prompt is classified
    #[serde(rename = "brand_kind", deserialize_with = "Option::deserialize")]
    pub brand_kind: Option<String>,
    /// Null until the prompt has run
    #[serde(rename = "last_executed_at", deserialize_with = "Option::deserialize")]
    pub last_executed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Opens this prompt in the app. The link names its project, so it opens there for any user with access to that project
    #[serde(rename = "app_url")]
    pub app_url: String,
}

impl PromptRecord {
    pub fn new(id: i32, prompt_text: String, collection_id: Option<i32>, collection_ids: Vec<i32>, tags: Vec<models::TagRef>, country_code: Option<String>, language_code: Option<String>, prompt_type: Option<String>, brand_kind: Option<String>, last_executed_at: Option<chrono::DateTime<chrono::FixedOffset>>, app_url: String) -> PromptRecord {
        PromptRecord {
            id,
            prompt_text,
            collection_id,
            collection_ids,
            tags,
            country_code,
            language_code,
            prompt_type,
            brand_kind,
            last_executed_at,
            app_url,
        }
    }
}

