/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PromptTagsAssignResponse {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// Prompts of the project among prompt_ids
    #[serde(rename = "prompts_targeted")]
    pub prompts_targeted: i32,
    #[serde(rename = "tags_attached")]
    pub tags_attached: Vec<models::TagRef>,
    #[serde(rename = "new_links_created")]
    pub new_links_created: i32,
    #[serde(rename = "skipped_already_linked")]
    pub skipped_already_linked: i32,
    /// tag_names that matched no tag and were not created
    #[serde(rename = "missing_tag_names")]
    pub missing_tag_names: Vec<String>,
    /// prompt_ids that are not prompts of this project
    #[serde(rename = "ignored_prompt_ids")]
    pub ignored_prompt_ids: Vec<i32>,
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl PromptTagsAssignResponse {
    pub fn new(project_id: i32, prompts_targeted: i32, tags_attached: Vec<models::TagRef>, new_links_created: i32, skipped_already_linked: i32, missing_tag_names: Vec<String>, ignored_prompt_ids: Vec<i32>, request_id: String) -> PromptTagsAssignResponse {
        PromptTagsAssignResponse {
            project_id,
            prompts_targeted,
            tags_attached,
            new_links_created,
            skipped_already_linked,
            missing_tag_names,
            ignored_prompt_ids,
            request_id,
        }
    }
}

