/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryWebAnalyticsRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// The query in the provider's native format (see GET /web_analytics/schema): a JSON object for GA4, Adobe, Matomo, Plausible and Piano; for PostHog, {\"query\": \"<HogQL>\"} or the HogQL string. Deliberately untyped so generated clients accept either shape.
    #[serde(rename = "query", deserialize_with = "Option::deserialize")]
    pub query: Option<serde_json::Value>,
}

impl QueryWebAnalyticsRequest {
    pub fn new(project_id: i32, query: Option<serde_json::Value>) -> QueryWebAnalyticsRequest {
        QueryWebAnalyticsRequest {
            project_id,
            query,
        }
    }
}

