/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationSummary {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "recommendation_type")]
    pub recommendation_type: RecommendationType,
    #[serde(rename = "status")]
    pub status: Status,
    /// Set only when status is failed
    #[serde(rename = "error_message", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
    /// Null until the generation completes
    #[serde(rename = "generated_at", deserialize_with = "Option::deserialize")]
    pub generated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "total_recommendations")]
    pub total_recommendations: i32,
    #[serde(rename = "high_priority_count")]
    pub high_priority_count: i32,
    #[serde(rename = "summary")]
    pub summary: Box<models::RecommendationSummarySummary>,
    /// Generation context and run diagnostics as stored; empty until the generation completes. Its keys are not a stable contract
    #[serde(rename = "context")]
    pub context: serde_json::Value,
}

impl RecommendationSummary {
    pub fn new(id: i32, project_id: i32, recommendation_type: RecommendationType, status: Status, error_message: Option<String>, generated_at: Option<chrono::DateTime<chrono::FixedOffset>>, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>, total_recommendations: i32, high_priority_count: i32, summary: models::RecommendationSummarySummary, context: serde_json::Value) -> RecommendationSummary {
        RecommendationSummary {
            id,
            project_id,
            recommendation_type,
            status,
            error_message,
            generated_at,
            created_at,
            updated_at,
            total_recommendations,
            high_priority_count,
            summary: Box::new(summary),
            context,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecommendationType {
    #[serde(rename = "ai_visibility")]
    AiVisibility,
    #[serde(rename = "social_community")]
    SocialCommunity,
    #[serde(rename = "brand_building")]
    BrandBuilding,
    #[serde(rename = "sentiment_reputation")]
    SentimentReputation,
}

impl Default for RecommendationType {
    fn default() -> RecommendationType {
        Self::AiVisibility
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "processing")]
    Processing,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

