/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecommendationSummarySummary : Empty until the generation completes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationSummarySummary {
    #[serde(rename = "total_recommendations", skip_serializing_if = "Option::is_none")]
    pub total_recommendations: Option<i32>,
    #[serde(rename = "high_priority_count", skip_serializing_if = "Option::is_none")]
    pub high_priority_count: Option<i32>,
    #[serde(rename = "categories", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Vec<String>>,
}

impl RecommendationSummarySummary {
    /// Empty until the generation completes
    pub fn new() -> RecommendationSummarySummary {
        RecommendationSummarySummary {
            total_recommendations: None,
            high_priority_count: None,
            categories: None,
        }
    }
}

