/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchConsoleFiltersInner {
    #[serde(rename = "dimension")]
    pub dimension: Dimension,
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<Operator>,
    #[serde(rename = "expression")]
    pub expression: String,
}

impl SearchConsoleFiltersInner {
    pub fn new(dimension: Dimension, expression: String) -> SearchConsoleFiltersInner {
        SearchConsoleFiltersInner {
            dimension,
            operator: None,
            expression,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Dimension {
    #[serde(rename = "country")]
    Country,
    #[serde(rename = "device")]
    Device,
    #[serde(rename = "page")]
    Page,
    #[serde(rename = "query")]
    Query,
    #[serde(rename = "searchAppearance")]
    SearchAppearance,
}

impl Default for Dimension {
    fn default() -> Dimension {
        Self::Country
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "contains")]
    Contains,
    #[serde(rename = "equals")]
    Equals,
    #[serde(rename = "notContains")]
    NotContains,
    #[serde(rename = "notEquals")]
    NotEquals,
    #[serde(rename = "includingRegex")]
    IncludingRegex,
    #[serde(rename = "excludingRegex")]
    ExcludingRegex,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::Contains
    }
}

