/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.56.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SentimentRecord {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "prompt_execution_id")]
    pub prompt_execution_id: i32,
    #[serde(rename = "prompt_text")]
    pub prompt_text: String,
    #[serde(rename = "model")]
    pub model: Model,
    #[serde(rename = "analysis")]
    pub analysis: Analysis,
    /// From -1 (very negative) to 1 (very positive)
    #[serde(rename = "score", deserialize_with = "Option::deserialize")]
    pub score: Option<f64>,
    #[serde(rename = "comment", deserialize_with = "Option::deserialize")]
    pub comment: Option<String>,
    /// Comma-separated topics
    #[serde(rename = "topics", deserialize_with = "Option::deserialize")]
    pub topics: Option<String>,
    /// Null for a sentiment about the project's own brand
    #[serde(rename = "competitor_id", deserialize_with = "Option::deserialize")]
    pub competitor_id: Option<i32>,
    /// Null for a sentiment about the project's own brand
    #[serde(rename = "competitor_name", deserialize_with = "Option::deserialize")]
    pub competitor_name: Option<String>,
    #[serde(rename = "is_brand_sentiment")]
    pub is_brand_sentiment: bool,
    #[serde(rename = "executed_at", deserialize_with = "Option::deserialize")]
    pub executed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SentimentRecord {
    pub fn new(id: i32, prompt_execution_id: i32, prompt_text: String, model: Model, analysis: Analysis, score: Option<f64>, comment: Option<String>, topics: Option<String>, competitor_id: Option<i32>, competitor_name: Option<String>, is_brand_sentiment: bool, executed_at: Option<chrono::DateTime<chrono::FixedOffset>>, created_at: chrono::DateTime<chrono::FixedOffset>) -> SentimentRecord {
        SentimentRecord {
            id,
            prompt_execution_id,
            prompt_text,
            model,
            analysis,
            score,
            comment,
            topics,
            competitor_id,
            competitor_name,
            is_brand_sentiment,
            executed_at,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Model {
    #[serde(rename = "chatgpt")]
    Chatgpt,
    #[serde(rename = "perplexity")]
    Perplexity,
    #[serde(rename = "ai_mode")]
    AiMode,
    #[serde(rename = "ai_overview")]
    AiOverview,
    #[serde(rename = "gemini")]
    Gemini,
    #[serde(rename = "copilot")]
    Copilot,
    #[serde(rename = "amazon_rufus")]
    AmazonRufus,
    #[serde(rename = "claude")]
    Claude,
    #[serde(rename = "grok")]
    Grok,
    #[serde(rename = "deepseek")]
    Deepseek,
    #[serde(rename = "naver_ai")]
    NaverAi,
    #[serde(rename = "baidu_ai")]
    BaiduAi,
    #[serde(rename = "meta_ai")]
    MetaAi,
}

impl Default for Model {
    fn default() -> Model {
        Self::Chatgpt
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Analysis {
    #[serde(rename = "very_positive")]
    VeryPositive,
    #[serde(rename = "positive")]
    Positive,
    #[serde(rename = "neutral")]
    Neutral,
    #[serde(rename = "negative")]
    Negative,
    #[serde(rename = "very_negative")]
    VeryNegative,
}

impl Default for Analysis {
    fn default() -> Analysis {
        Self::VeryPositive
    }
}

