/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SovResponseBreakdownInner {
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<i32>,
    #[serde(rename = "actor", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Box<models::Actor>>,
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<f64>,
    #[serde(rename = "others", skip_serializing_if = "Option::is_none")]
    pub others: Option<bool>,
}

impl SovResponseBreakdownInner {
    pub fn new() -> SovResponseBreakdownInner {
        SovResponseBreakdownInner {
            rank: None,
            actor: None,
            share: None,
            others: None,
        }
    }
}

