/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SovResponsePeriodsInner {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<chrono::NaiveDate>,
    #[serde(rename = "mentions", skip_serializing_if = "Option::is_none")]
    pub mentions: Option<i32>,
    #[serde(rename = "partial", skip_serializing_if = "Option::is_none")]
    pub partial: Option<bool>,
}

impl SovResponsePeriodsInner {
    pub fn new() -> SovResponsePeriodsInner {
        SovResponsePeriodsInner {
            date: None,
            mentions: None,
            partial: None,
        }
    }
}

