/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SovResponseCurrentInner {
    #[serde(rename = "actor", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Box<models::Actor>>,
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<f64>,
    /// The actor's share in the last complete bucket before the current one; null without complete history.
    #[serde(rename = "previous_share", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous_share: Option<Option<f64>>,
    /// Mean share across complete buckets with data (partial buckets excluded); null without complete history.
    #[serde(rename = "avg_share", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avg_share: Option<Option<f64>>,
}

impl SovResponseCurrentInner {
    pub fn new() -> SovResponseCurrentInner {
        SovResponseCurrentInner {
            actor: None,
            share: None,
            previous_share: None,
            avg_share: None,
        }
    }
}

