/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StoreConnectionResponseProject : The live project the store maps to: its domain equals the store's, or is a parent or subdomain of it. Null when no project matches
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreConnectionResponseProject {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "country_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<Option<String>>,
    #[serde(rename = "language_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub language_code: Option<Option<String>>,
}

impl StoreConnectionResponseProject {
    /// The live project the store maps to: its domain equals the store's, or is a parent or subdomain of it. Null when no project matches
    pub fn new(id: i32, name: String, domain: String) -> StoreConnectionResponseProject {
        StoreConnectionResponseProject {
            id,
            name,
            domain,
            country_code: None,
            language_code: None,
        }
    }
}

