/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreConnectionResponseCandidatesInner {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    /// Empty when the project has no website URL
    #[serde(rename = "domain")]
    pub domain: String,
}

impl StoreConnectionResponseCandidatesInner {
    pub fn new(id: i32, name: String, domain: String) -> StoreConnectionResponseCandidatesInner {
        StoreConnectionResponseCandidatesInner {
            id,
            name,
            domain,
        }
    }
}

