/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryResponseAllOfPositionDistribution {
    #[serde(rename = "position_1_count", skip_serializing_if = "Option::is_none")]
    pub position_1_count: Option<i32>,
    #[serde(rename = "position_2_count", skip_serializing_if = "Option::is_none")]
    pub position_2_count: Option<i32>,
    #[serde(rename = "position_3_plus_count", skip_serializing_if = "Option::is_none")]
    pub position_3_plus_count: Option<i32>,
    #[serde(rename = "total_mentions", skip_serializing_if = "Option::is_none")]
    pub total_mentions: Option<i32>,
    #[serde(rename = "percentages", skip_serializing_if = "Option::is_none")]
    pub percentages: Option<serde_json::Value>,
}

impl SummaryResponseAllOfPositionDistribution {
    pub fn new() -> SummaryResponseAllOfPositionDistribution {
        SummaryResponseAllOfPositionDistribution {
            position_1_count: None,
            position_2_count: None,
            position_3_plus_count: None,
            total_mentions: None,
            percentages: None,
        }
    }
}

