/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryResponseAllOfSummaryValueInner {
    #[serde(rename = "actor", skip_serializing_if = "Option::is_none")]
    pub actor: Option<Box<models::Actor>>,
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<String>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f64>,
    /// How total combines the buckets
    #[serde(rename = "aggregation", skip_serializing_if = "Option::is_none")]
    pub aggregation: Option<Aggregation>,
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(rename = "last", skip_serializing_if = "Option::is_none")]
    pub last: Option<f64>,
}

impl SummaryResponseAllOfSummaryValueInner {
    pub fn new() -> SummaryResponseAllOfSummaryValueInner {
        SummaryResponseAllOfSummaryValueInner {
            actor: None,
            metric: None,
            total: None,
            aggregation: None,
            min: None,
            max: None,
            last: None,
        }
    }
}
/// How total combines the buckets
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Aggregation {
    #[serde(rename = "sum")]
    Sum,
    #[serde(rename = "average")]
    Average,
}

impl Default for Aggregation {
    fn default() -> Aggregation {
        Self::Sum
    }
}

