/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.55.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TechnicalGeoReportContentRevertRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    /// Only llms_txt reports have editable content
    #[serde(rename = "report_type")]
    pub report_type: ReportType,
}

impl TechnicalGeoReportContentRevertRequest {
    pub fn new(project_id: i32, report_type: ReportType) -> TechnicalGeoReportContentRevertRequest {
        TechnicalGeoReportContentRevertRequest {
            project_id,
            report_type,
        }
    }
}
/// Only llms_txt reports have editable content
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportType {
    #[serde(rename = "llms_txt")]
    LlmsTxt,
}

impl Default for ReportType {
    fn default() -> ReportType {
        Self::LlmsTxt
    }
}

