/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.48.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeseriesPoint {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
}

impl TimeseriesPoint {
    pub fn new() -> TimeseriesPoint {
        TimeseriesPoint {
            date: None,
            value: None,
        }
    }
}

