/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeseriesResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "granularity", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<String>,
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<serde_json::Value>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<std::collections::HashMap<String, Vec<models::TimeseriesSeries>>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl TimeseriesResponse {
    pub fn new() -> TimeseriesResponse {
        TimeseriesResponse {
            project_id: None,
            from: None,
            to: None,
            granularity: None,
            filters: None,
            series: None,
            request_id: None,
        }
    }
}

