/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopSourcesResponseDataInner {
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "total_responses", skip_serializing_if = "Option::is_none")]
    pub total_responses: Option<i32>,
    #[serde(rename = "avg_visibility", skip_serializing_if = "Option::is_none")]
    pub avg_visibility: Option<f64>,
    #[serde(rename = "avg_mention_rate", skip_serializing_if = "Option::is_none")]
    pub avg_mention_rate: Option<f64>,
}

impl TopSourcesResponseDataInner {
    pub fn new() -> TopSourcesResponseDataInner {
        TopSourcesResponseDataInner {
            domain: None,
            total_responses: None,
            avg_visibility: None,
            avg_mention_rate: None,
        }
    }
}

