/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCompetitorRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    /// Hex color, e.g. #1a2b3c
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
}

impl UpdateCompetitorRequest {
    pub fn new(project_id: i32) -> UpdateCompetitorRequest {
        UpdateCompetitorRequest {
            project_id,
            brand_name: None,
            matching_names: None,
            color: None,
        }
    }
}

