/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.22.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectDraftRequest {
    #[serde(rename = "step")]
    pub step: Step,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<Vec<String>>,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    #[serde(rename = "external_identifier", skip_serializing_if = "Option::is_none")]
    pub external_identifier: Option<String>,
    #[serde(rename = "prompts", skip_serializing_if = "Option::is_none")]
    pub prompts: Option<Vec<String>>,
    #[serde(rename = "competitors", skip_serializing_if = "Option::is_none")]
    pub competitors: Option<Vec<serde_json::Value>>,
    #[serde(rename = "youtube_channel_url", skip_serializing_if = "Option::is_none")]
    pub youtube_channel_url: Option<String>,
    #[serde(rename = "instagram_profile_url", skip_serializing_if = "Option::is_none")]
    pub instagram_profile_url: Option<String>,
    #[serde(rename = "facebook_page_url", skip_serializing_if = "Option::is_none")]
    pub facebook_page_url: Option<String>,
    #[serde(rename = "tiktok_profile_url", skip_serializing_if = "Option::is_none")]
    pub tiktok_profile_url: Option<String>,
    #[serde(rename = "app_store_url", skip_serializing_if = "Option::is_none")]
    pub app_store_url: Option<String>,
    #[serde(rename = "google_play_url", skip_serializing_if = "Option::is_none")]
    pub google_play_url: Option<String>,
    #[serde(rename = "suggest", skip_serializing_if = "Option::is_none")]
    pub suggest: Option<bool>,
}

impl UpdateProjectDraftRequest {
    pub fn new(step: Step) -> UpdateProjectDraftRequest {
        UpdateProjectDraftRequest {
            step,
            name: None,
            brand_name: None,
            description: None,
            industry: None,
            matching_names: None,
            external_identifier: None,
            prompts: None,
            competitors: None,
            youtube_channel_url: None,
            instagram_profile_url: None,
            facebook_page_url: None,
            tiktok_profile_url: None,
            app_store_url: None,
            google_play_url: None,
            suggest: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Step {
    #[serde(rename = "details")]
    Details,
    #[serde(rename = "prompts")]
    Prompts,
    #[serde(rename = "competitors")]
    Competitors,
    #[serde(rename = "owned_media")]
    OwnedMedia,
}

impl Default for Step {
    fn default() -> Step {
        Self::Details
    }
}

