/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAnnotationRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "annotation_date", skip_serializing_if = "Option::is_none")]
    pub annotation_date: Option<chrono::NaiveDate>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "annotation_category_id", skip_serializing_if = "Option::is_none")]
    pub annotation_category_id: Option<i32>,
}

impl UpdateAnnotationRequest {
    pub fn new(project_id: i32) -> UpdateAnnotationRequest {
        UpdateAnnotationRequest {
            project_id,
            title: None,
            description: None,
            annotation_date: None,
            color: None,
            annotation_category_id: None,
        }
    }
}

