/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.46.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCompetitorRequest {
    #[serde(rename = "project_id")]
    pub project_id: i32,
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    /// Website domain or host used for citation matching. A full URL is accepted and normalised to its host.
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
    /// Hex color, e.g. #1a2b3c
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "citation_match_mode", skip_serializing_if = "Option::is_none")]
    pub citation_match_mode: Option<CitationMatchMode>,
    /// Required when changing citation_match_mode to path_prefix
    #[serde(rename = "citation_match_path", skip_serializing_if = "Option::is_none")]
    pub citation_match_path: Option<String>,
}

impl UpdateCompetitorRequest {
    pub fn new(project_id: i32) -> UpdateCompetitorRequest {
        UpdateCompetitorRequest {
            project_id,
            brand_name: None,
            domain: None,
            matching_names: None,
            color: None,
            citation_match_mode: None,
            citation_match_path: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CitationMatchMode {
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "host")]
    Host,
    #[serde(rename = "path_prefix")]
    PathPrefix,
}

impl Default for CitationMatchMode {
    fn default() -> CitationMatchMode {
        Self::Domain
    }
}

