/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.47.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProjectRequest {
    /// Brand name used to detect mentions. Applies to future runs; it does not rewrite history
    #[serde(rename = "brand_name", skip_serializing_if = "Option::is_none")]
    pub brand_name: Option<String>,
    /// What the brand does. Context for Recommendations and GEO Writer (Brand Book)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Single industry key (e.g. SAAS); unknown keys are rejected
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    /// Business model key (e.g. B2B_SAAS); unknown keys are rejected
    #[serde(rename = "business_model", skip_serializing_if = "Option::is_none")]
    pub business_model: Option<String>,
    /// Free-text business model, only accepted when business_model is OTHER; rejected against any other key
    #[serde(rename = "business_model_other", skip_serializing_if = "Option::is_none")]
    pub business_model_other: Option<String>,
    /// Who the brand sells to (Brand Book)
    #[serde(rename = "target_audience", skip_serializing_if = "Option::is_none")]
    pub target_audience: Option<String>,
    /// Tone of voice guidance for generated content (Brand Book)
    #[serde(rename = "brand_voice", skip_serializing_if = "Option::is_none")]
    pub brand_voice: Option<String>,
    /// What the brand wants to achieve. Context for GEO Writer and prompt suggestions
    #[serde(rename = "goals", skip_serializing_if = "Option::is_none")]
    pub goals: Option<String>,
    /// Full replacement list of the main products or services
    #[serde(rename = "primary_products", skip_serializing_if = "Option::is_none")]
    pub primary_products: Option<Vec<String>>,
    /// FULL replacement list of the brand-name variants used to detect mentions; send every variant to keep
    #[serde(rename = "matching_names", skip_serializing_if = "Option::is_none")]
    pub matching_names: Option<Vec<String>>,
}

impl UpdateProjectRequest {
    pub fn new() -> UpdateProjectRequest {
        UpdateProjectRequest {
            brand_name: None,
            description: None,
            industry: None,
            business_model: None,
            business_model_other: None,
            target_audience: None,
            brand_voice: None,
            goals: None,
            primary_products: None,
            matching_names: None,
        }
    }
}

