/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAnalyticsSchemaResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    /// The connected web analytics provider.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Provider>,
    /// The property, site, report suite (rsid:...), data view (dataview:...) or project every query runs on.
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    /// The native query format the provider accepts.
    #[serde(rename = "query_language", skip_serializing_if = "Option::is_none")]
    pub query_language: Option<String>,
    /// The provider's reference for that format.
    #[serde(rename = "docs_url", skip_serializing_if = "Option::is_none")]
    pub docs_url: Option<String>,
    /// Top-level query fields that are forwarded.
    #[serde(rename = "allowed_fields", skip_serializing_if = "Option::is_none")]
    pub allowed_fields: Option<Vec<String>>,
    /// What the bridge enforces and the provider's main constraints.
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<String>>,
    /// A worked query to adapt.
    #[serde(rename = "example", skip_serializing_if = "Option::is_none")]
    pub example: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The provider's live field list where it offers one: GA4 dimensions and metrics with custom definitions, Adobe ids, Matomo report methods, PostHog event names, the Plausible catalog. Null when the provider did not return it.
    #[serde(rename = "fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Present when the field list could not be read; the format and example still apply.
    #[serde(rename = "fields_unavailable", skip_serializing_if = "Option::is_none")]
    pub fields_unavailable: Option<String>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl WebAnalyticsSchemaResponse {
    pub fn new() -> WebAnalyticsSchemaResponse {
        WebAnalyticsSchemaResponse {
            project_id: None,
            provider: None,
            property: None,
            query_language: None,
            docs_url: None,
            allowed_fields: None,
            rules: None,
            example: None,
            fields: None,
            fields_unavailable: None,
            request_id: None,
        }
    }
}
/// The connected web analytics provider.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "google_analytics")]
    GoogleAnalytics,
    #[serde(rename = "adobe_analytics")]
    AdobeAnalytics,
    #[serde(rename = "matomo")]
    Matomo,
    #[serde(rename = "posthog")]
    Posthog,
    #[serde(rename = "plausible")]
    Plausible,
    #[serde(rename = "piano")]
    Piano,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::GoogleAnalytics
    }
}

