/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAnalyticsQueryResponseColumnsInner {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// dimension or metric, when the provider says.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// The provider's column type, when it says (PostHog).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The provider's display label, when it sends one (Piano).
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl WebAnalyticsQueryResponseColumnsInner {
    pub fn new() -> WebAnalyticsQueryResponseColumnsInner {
        WebAnalyticsQueryResponseColumnsInner {
            name: None,
            kind: None,
            r#type: None,
            label: None,
        }
    }
}

