/*
 * LLM Pulse API
 *
 * REST API client for LLM Pulse AI visibility analytics.
 *
 * The version of the OpenAPI document: 1.57.0
 * Contact: info@llmpulse.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebAnalyticsQueryResponse {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Provider>,
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,
    #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Vec<models::WebAnalyticsQueryResponseColumnsInner>>,
    /// One array per row, values in column order: strings, numbers or null.
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<Vec<serde_json::Value>>>,
    /// Rows in this response (at most 5,000).
    #[serde(rename = "row_count", skip_serializing_if = "Option::is_none")]
    pub row_count: Option<i32>,
    /// Rows the provider has for the query, when it reports it.
    #[serde(rename = "total_rows", skip_serializing_if = "Option::is_none")]
    pub total_rows: Option<i32>,
    /// True when the provider has more rows than returned; page with its own offset or page field.
    #[serde(rename = "truncated", skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    /// Metric totals by metric name, when the query asked for them.
    #[serde(rename = "totals", skip_serializing_if = "Option::is_none")]
    pub totals: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Provider caveats: sampling, thresholds, more rows available.
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<String>>,
    /// Provider metadata such as GA4 time zone, currency and remaining property quota.
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// When the provider answered.
    #[serde(rename = "fetched_at", skip_serializing_if = "Option::is_none")]
    pub fetched_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// True when the answer came from the 10-minute cache instead of the provider.
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
    /// The request as sent to the provider, with the connected property forced and limits applied.
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl WebAnalyticsQueryResponse {
    pub fn new() -> WebAnalyticsQueryResponse {
        WebAnalyticsQueryResponse {
            project_id: None,
            provider: None,
            property: None,
            columns: None,
            rows: None,
            row_count: None,
            total_rows: None,
            truncated: None,
            totals: None,
            notes: None,
            meta: None,
            fetched_at: None,
            cached: None,
            query: None,
            request_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "google_analytics")]
    GoogleAnalytics,
    #[serde(rename = "adobe_analytics")]
    AdobeAnalytics,
    #[serde(rename = "matomo")]
    Matomo,
    #[serde(rename = "posthog")]
    Posthog,
    #[serde(rename = "plausible")]
    Plausible,
    #[serde(rename = "piano")]
    Piano,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::GoogleAnalytics
    }
}

